### ISSUE TITLE
I'd like to use functions in DataFrame_read.tcc

### ISSUE THREAD

**Issue by kylehslee** [hosseinmoein/DataFrame#101]
How'd I use functions in DataFrame/include/DataFrame/Internals/*.tcc ?

**Comment by hosseinmoein** [comment]
Everything in `DataFrame/include/DataFrame/Internals` is meant for internal DataFrame usage. It should not/could not be accessed by a library user.

What exactly do you want to use from there?

**Comment by kylehslee** [comment]
Oh, thank you for real fast replying.
Actually, I was making a function for read_csv like pandas in python, but there was actually read_csv_(std::ifsteam file, bool columnOnly).

I kind of understand "DataFrame/include/DataFrame/Internals is meant for internal DataFrame usage", then how could I use read_csv_ function?

**Comment by hosseinmoein** [comment]
DataFrame has two public methods `read` and `write`, that you can use
The docs and code samples are here README (https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html)

**Comment by kylehslee** [comment]
Should've read docs carefully, I so much appreciate it.

**Comment by kylehslee** [comment]
Closed.
