### ISSUE TITLE
DateTime comparsion returns wrong result if two datetime are constructed from two different ways

### ISSUE THREAD

**Issue by fanxinping** [hosseinmoein/DataFrame#105]
Hi,

I meet a bug when use `DateTime` libray. Below is a simple example.
```c++
#include <iostream>
#include <DataFrame/Utils/DateTime.h>

int main(void) {
    hmdf::DateTime date1("2015/01/05 09:40:00", hmdf::DT_DATE_STYLE::EUR_STYLE);
    hmdf::DateTime date2;
    date2 = "20150105 09:40:00";
    if (date1 == date2) {
        std::cout << date1 << " is equal to " << date2 << std::endl;
    } else {
        std::cout << date1 << " is not equal to " << date2 << std::endl;
    }
    return 0;
}
``` 
And the output is:
```
01/05/2015 09:40:00.000 is not equal to 01/05/2015 09:40:00.000
```
In my code, `date1` and `date2` is the same time, but `==` operator returns wrong result. The difference between `date1` and `date2` is that I use the assignment operator to change value of `date2` after constructor.
After debugging and reading source code of `DateTime` library, I found that `==` operator uses `time_` and `nanosec` to check if two `DateTime` are equal eventually. In the assignment operator, `time_` is not update accord to left hand side, which causes `==`operator given wrong result.
Below is a screenshot of debugging.
![image](https://user-images.githubusercontent.com/23021820/111127396-c3294e80-85ae-11eb-9d47-e47ebde941dc.png)
As you can see, after assignment operator, `date_`, `hour_`, `minute_` is update but `time_` is not.

Please fix this bug.
Thanks!

**Comment by hosseinmoein** [comment]
Thanks for reporting this.
It is fixed in master
