### ISSUE TITLE
How does writing to.csv file work?

### ISSUE THREAD

**Issue by Asocius** [hosseinmoein/DataFrame#109]
Hello,

I just wanted to print the dataframe to an .csv file, and tried the following commands:

testframe.write<std::ostream, std::string, int>("Spagetti.csv", hmdf::io_format::csv2);
testframe.write<std::ostream, std::string, int>("D:/programming_stuff/Spagetti.csv", hmdf::io_format::csv2);

and also

testframe.write<std::ostream, std::string, int>(intoCSTR("Spagetti.csv"), hmdf::io_format::csv2);

where intoCSTR is a function that returns the string as a c-string.

Neither of those seems to work, so what am I doing wrong?

Best regards
Stephan

**Comment by hosseinmoein** [comment]
When you say _it doesn't work_, what do you mean, what happens?
Also, I assume the DataFrame you are writing only has columns of type `std::string` and `int`. For example, if you have a column of type `double`, and you don't specify `double` in the type list, that column won't be written. Each type needs to be specified only once. 
This is the doc for `write()`
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/write.html

**Comment by hosseinmoein** [comment]
Also, you do not need to specify `std::ostream`, since you are using a `write()` version that takes a file name. There is another `write()` that takes a stream. In that version you need to specify the stream type (e.g. `std::ostream`)
Again, look at the docs

**Comment by Asocius** [comment]
I also tried without the std::ostream and it still does not work. By not working I mean there are build errors. For

testframe.write<std::string, int>("Spagetti.csv", hmdf::io_format::csv2);

it gives the following error:

FAILED: CMakeFiles/Finder.dir/main.cpp.obj 
  C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe  /nologo /TP -DHMDF_SHARED -DLIBRARY_EXPORTS -D_CRT_SECURE_NO_WARNINGS -I..\..\..\include /DWIN32 /D_WINDOWS /W3 /GR /EHsc /bigobj /wd4251 /MDd /Zi /Ob0 /Od /RTC1 -std:c++17 /showIncludes /FoCMakeFiles\Finder.dir\main.cpp.obj /FdCMakeFiles\Finder.dir\ /FS -c ..\..\..\main.cpp
D:\06-PROGRAMMDATEIEN\Visual Studio\CMakeProject1\main.cpp(37): error C2664: 'bool hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::write<std::ostream,std::string,int>(S &,hmdf::io_format) const': cannot convert argument 1 from 'const char [13]' to 'S &'
          with
          [
              S=std::ostream
          ]
  D:\06-PROGRAMMDATEIEN\Visual Studio\CMakeProject1\include\DataFrame/Internals/DataFrame_write.tcc(39): note: see declaration of 'hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::write'
D:\06-PROGRAMMDATEIEN\Visual Studio\CMakeProject1\main.cpp(91): warning C4267: 'argument': conversion from 'size_t' to 'const unsigned long', possible loss of data
D:\06-PROGRAMMDATEIEN\Visual Studio\CMakeProject1\main.cpp(203): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
  ninja: build stopped: subcommand failed.

So it assumes I want to use an outputstream but I don't.

By the way, the testframe looks like this:

INDEX:3:<ulong>,firstColumn:3:<string>,secondColumn:3:<int>
0,abcd,64
1,efgh,132
2,ijkl,264

I looked at the docs but can't figure out what is wrong

**Comment by hosseinmoein** [comment]
hmm, I cannot replicate that on my macbook currently. try to explicitly cast the first argument to `const char *`:
```
testframe.write<std::string, int>((const char *) "Spagetti.csv", hmdf::io_format::csv2);
```

**Comment by Asocius** [comment]
Ok I can't make it work (I'm on Windows), even with explicit casting, thanks for the help. I'll look at it again when I have more time.

**Comment by hosseinmoein** [comment]
@Asocius ,
I was able to replicate the problem on a Linux laptop. I just pushed a fix to master. your original code should work now. Just take out the `std::ostream` from your type list
