### ISSUE TITLE
[help] concat always return StdDataFrame

### ISSUE THREAD

**Issue by westfly** [hosseinmoein/DataFrame#117]
Hi

I have two DataFrame with same column names need to merge, Concat with concat_policy::all_columns will work fine, but concat return a StdDataFrame will copy all data of two DataFrame which may cause performance issues, could you add an View interface ?

*self_concat* will modify the first DataFrame， but we want to keep the original DF.

thanks for your great work in advance.

**Comment by hosseinmoein** [comment]
Yeah, it is possible. I will take me a sometime to add it

**Comment by hosseinmoein** [comment]
This has been added to master.
See: https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/concat.html
