### ISSUE TITLE
fail in windows7, vs2019, C++17

### ISSUE THREAD

**Issue by xkungfu** [hosseinmoein/DataFrame#119]
windows7, vs2019, C++17

`

1>test1.cpp

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\DataFrameTypes.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(509,17): warning C4251: “hmdf::VectorPtrView<T>::vector_”: class“std::vector<T*,std::allocator<T*>>”需要有 dll 接口由 class“hmdf::VectorPtrView<T>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(55): message : 参见“std::vector<T*,std::allocator<T*>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(510): message : 查看对正在编译的 类 模板 实例化“hmdf::VectorPtrView<T>”的引用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(806,17): warning C4251: “hmdf::VectorConstPtrView<T>::vector_”: class“std::vector<const T*,std::allocator<const T*>>”需要有 dll 接口由 class“hmdf::VectorConstPtrView<T>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(517): message : 参见“std::vector<const T*,std::allocator<const T*>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(807): message : 查看对正在编译的 类 模板 实例化“hmdf::VectorConstPtrView<T>”的引用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(144,9): warning C4251: “hmdf::HeteroPtrView::views_”: class“std::unordered_map<const hmdf::HeteroPtrView*,hmdf::VectorPtrView<T>,std::hash<const hmdf::HeteroPtrView *>,std::equal_to<const hmdf::HeteroPtrView *>,std::allocator<std::pair<const hmdf::HeteroPtrView*const ,hmdf::VectorPtrView<T>>>>”需要有 dll 接口由 struct“hmdf::HeteroPtrView”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(143): message : 参见“std::unordered_map<const hmdf::HeteroPtrView*,hmdf::VectorPtrView<T>,std::hash<const hmdf::HeteroPtrView *>,std::equal_to<const hmdf::HeteroPtrView *>,std::allocator<std::pair<const hmdf::HeteroPtrView*const ,hmdf::VectorPtrView<T>>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(147,9): warning C4251: “hmdf::HeteroPtrView::clear_function_”: class“std::function<void (hmdf::HeteroPtrView &)>”需要有 dll 接口由 struct“hmdf::HeteroPtrView”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(146): message : 参见“std::function<void (hmdf::HeteroPtrView &)>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(151,9): warning C4251: “hmdf::HeteroPtrView::copy_function_”: class“std::function<void (const hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>”需要有 dll 接口由 struct“hmdf::HeteroPtrView”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(150): message : 参见“std::function<void (const hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(155,9): warning C4251: “hmdf::HeteroPtrView::move_function_”: class“std::function<void (hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>”需要有 dll 接口由 struct“hmdf::HeteroPtrView”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(154): message : 参见“std::function<void (hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.tcc(101,20): error C2039: "runtime_error": 不是 "std" 的成员

1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\iterator(21): message : 参见“std”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroPtrView.h(75,23): message : 此诊断出现在编译器生成的函数“hmdf::VectorPtrView<T> &hmdf::HeteroPtrView::get_vector(void)”中

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroView.tcc(77,20): error C2039: "runtime_error": 不是 "std" 的成员

1>D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\iterator(21): message : 参见“std”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\HeteroView.h(71,20): message : 此诊断出现在编译器生成的函数“hmdf::VectorView<T> &hmdf::HeteroView::get_vector(void)”中

1>I:\C++\libs\dataframe\include\DataFrame\Utils\DateTime.h(406,41): warning C4251: “hmdf::DateTime::dt_init_”: struct“hmdf::DateTime::DT_initializer”需要有 dll 接口由 class“hmdf::DateTime”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Utils\DateTime.h(396): message : 参见“hmdf::DateTime::DT_initializer”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_standalone.tcc(638,11): error C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizePriorityQueue.h(45,1): warning C4005: “LIBRARY_API”: 宏重定义

1>I:\C++\libs\dataframe\include\DataFrame\Vectors\VectorPtrView.h(41): message : 参见“LIBRARY_API”的前一个定义

1>I:\C++\libs\dataframe\include\DataFrame\Utils\ThreadGranularity.h(41,1): warning C4005: “LIBRARY_API”: 宏重定义

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizePriorityQueue.h(45): message : 参见“LIBRARY_API”的前一个定义

1>I:\C++\libs\dataframe\include\DataFrame\DataFrameStatsVisitors.h(976,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizeString.h(99,11): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizeString.h(118,11): error C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizeString.h(207,29): error C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

1>I:\C++\libs\dataframe\include\DataFrame\Utils\FixedSizeString.h(220,15): error C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(2325,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3099,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3175,21): warning C4251: “hmdf::DataFrame<I,H>::data_”: class“std::vector<H,std::allocator<_Other>>”需要有 dll 接口由 class“hmdf::DataFrame<I,H>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(73): message : 参见“std::vector<H,std::allocator<_Other>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3193): message : 查看对正在编译的 类 模板 实例化“hmdf::DataFrame<I,H>”的引用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3177,21): warning C4251: “hmdf::DataFrame<I,H>::column_tb_”: class“std::unordered_map<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>”需要有 dll 接口由 class“hmdf::DataFrame<I,H>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3170): message : 参见“std::unordered_map<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3182,21): warning C4251: “hmdf::DataFrame<I,H>::column_list_”: class“std::vector<std::pair<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>,std::allocator<std::pair<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>”需要有 dll 接口由 class“hmdf::DataFrame<I,H>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3171): message : 参见“std::vector<std::pair<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>,std::allocator<std::pair<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame.tcc(44,19): error C2491: “hmdf::DataFrame<I,H>::~DataFrame”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame.tcc(54,23): error C2491: “hmdf::DataFrame<I,H>::empty”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame.tcc(60,1): error C2491: “hmdf::DataFrame<I,H>::shapeless”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame.tcc(65,23): error C2491: “hmdf::DataFrame<I,H>::set_lock”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame.tcc(70,23): error C2491: “hmdf::DataFrame<I,H>::remove_lock”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_get.tcc(46,18): error C2491: “hmdf::DataFrame<I,H>::shape”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_get.tcc(106,23): error C2491: “hmdf::DataFrame<I,H>::has_column”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_get.tcc(117,1): error C2491: “hmdf::DataFrame<I,H>::has_column”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_get.tcc(143,18): error C2491: “hmdf::DataFrame<I,H>::get_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_get.tcc(149,18): error C2491: “hmdf::DataFrame<I,H>::get_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3175,21): warning C4251: “hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::data_”: class“std::vector<hmdf::HeteroVector,std::allocator<hmdf::HeteroVector>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned int,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(73): message : 参见“std::vector<hmdf::HeteroVector,std::allocator<hmdf::HeteroVector>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_join.tcc(248): message : 查看对正在编译的 类 模板 实例化“hmdf::DataFrame<unsigned int,hmdf::HeteroVector>”的引用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3176,21): warning C4251: “hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::indices_”: class“std::vector<unsigned int,std::allocator<unsigned int>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned int,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_standalone.tcc(740): message : 参见“std::vector<unsigned int,std::allocator<unsigned int>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3177,21): warning C4251: “hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::column_tb_”: class“std::unordered_map<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned int,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3170): message : 参见“std::unordered_map<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3182,21): warning C4251: “hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::column_list_”: class“std::vector<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>,std::allocator<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned int,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3171): message : 参见“std::vector<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>,std::allocator<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_read.tcc(49,23): error C2491: “hmdf::DataFrame<I,H>::read_json_”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_read.tcc(283,23): error C2491: “hmdf::DataFrame<I,H>::read_csv_”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_read.tcc(435,23): error C2491: “hmdf::DataFrame<I,H>::read_csv2_”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_read.tcc(732,1): error C2491: “hmdf::DataFrame<I,H>::read”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_read.tcc(774,1): error C2491: “hmdf::DataFrame<I,H>::read_async”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(69,23): error C2491: “hmdf::DataFrame<I,H>::remove_column”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(106,23): error C2491: “hmdf::DataFrame<I,H>::remove_column”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(114,23): error C2491: “hmdf::DataFrame<I,H>::rename_column”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(220,18): error C2491: “hmdf::DataFrame<I,H>::load_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(233,1): error C2491: “hmdf::DataFrame<I,H>::gen_datetime_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(291,1): error C2491: “hmdf::DataFrame<I,H>::gen_sequence_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_set.tcc(325,18): error C2491: “hmdf::DataFrame<I,H>::append_index”: 不允许 dllimport 函数 的定义

1>I:\C++\libs\dataframe\include\DataFrame\RandGen.h(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3175,21): warning C4251: “hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::data_”: class“std::vector<hmdf::HeteroVector,std::allocator<hmdf::HeteroVector>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned long,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(73): message : 参见“std::vector<hmdf::HeteroVector,std::allocator<hmdf::HeteroVector>>”的声明

1>I:\C++\CodeStation\Repos\dataframe-test\demo\demo\test1.cpp(55): message : 查看对正在编译的 类 模板 实例化“hmdf::DataFrame<unsigned long,hmdf::HeteroVector>”的引用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3176,21): warning C4251: “hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::indices_”: class“std::vector<unsigned long,std::allocator<unsigned long>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned long,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\Internals\DataFrame_standalone.tcc(753): message : 参见“std::vector<unsigned long,std::allocator<unsigned long>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3177,21): warning C4251: “hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::column_tb_”: class“std::unordered_map<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned long,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3170): message : 参见“std::unordered_map<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”的声明

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3182,21): warning C4251: “hmdf::DataFrame<unsigned long,hmdf::HeteroVector>::column_list_”: class“std::vector<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>,std::allocator<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”需要有 dll 接口由 class“hmdf::DataFrame<unsigned long,hmdf::HeteroVector>”的客户端使用

1>I:\C++\libs\dataframe\include\DataFrame\DataFrame.h(3171): message : 参见“std::vector<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>,std::allocator<std::pair<hmdf::DataFrame<unsigned int,hmdf::HeteroVector>::ColNameType,unsigned __int64>>>”的声明

`

**Comment by hosseinmoein** [comment]
1. Half of your printout is in Chinese. I cannot read it.
2. How do you compile it? Are you following the CMake instructions in README? Alternatively, you could use Conan
3. Is your OS 32bits? This won't work on 32bit arch

**Comment by xkungfu** [comment]
INSTALL:

```
1.  Open "x64 Native Tools Command Prompt for VS 2019"

2.  mkdir release
3.  cd I:\C++\libs\__dataframe\DataFrame-master\DataFrame-master\release

4.  cmake -G "NMake Makefiles" -D CMAKE_INSTALL_PREFIX=I:\C++\libs\dataframe  ..

5.  nmake
6.  nmake install
```

**vs2019 project setup：**

```
C++ additional directory：
I:\C++\libs\dataframe\include

C++ additional library directory：
I:\C++\libs\dataframe\lib

additional dependencies：
DataFrame.lib

```

demo code:

```
#include <DataFrame/DataFrame.h>
#include <cassert>
#include <cmath>
#include <iostream>
#include <limits>
#include <string>
#include <typeinfo>

using namespace hmdf;

using MyDataFrame = StdDataFrame<unsigned long>;

int main(int argc, char* argv[]) {

    std::cout << "\nTesting read() ..." << std::endl;

    MyDataFrame df_read;

    try {
        std::future<bool>   fut2 = df_read.read_async("000001.csv");

        fut2.get();
    }
    catch (const DataFrameError& ex) {
        std::cout << ex.what() << std::endl;
    }

    return (0);
}
```


That is all. anything wrong in my steps?

**Comment by westfly** [comment]
maybe you can try [vcpkg](https://github.com/microsoft/vcpkg) which developing by microsoft to build by yourself @xkungfu
