### ISSUE TITLE
Need help for Build for IOS 

### ISSUE THREAD

**Issue by zulfiker** [hosseinmoein/DataFrame#12]
I want to build this project for ios in xcode . I was able to build for mac and generate .**dylib** using cmake . Can i build it using cmake with little modification and . or can i build from source ? is there any dependencies ?

**Comment by zulfiker** [comment]
**dylib**

**Comment by hosseinmoein** [comment]
This project is completely self contained. So there are no external library dependency.
If you end up modifying the source code or make process, give me a pull request so I can include it.

**Comment by hosseinmoein** [comment]
If you are ok, I am closing this issue
