### ISSUE TITLE
[help] Get sub DataFrame by column_name for Groupby

### ISSUE THREAD

**Issue by westfly** [hosseinmoein/DataFrame#122]
We have a big DataFrame, but only care a few column for groupby which may cost time，so we generate sub DataFrame to groupby. 

we check api, get_data_by_idx get_data_by_loc will work，but we must keep idx of column outside. Is it possible to add interface by column_names ?

**Comment by hosseinmoein** [comment]
I am not sure I understand what you are asking. Can you explain further, ideally with an example?
