### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by hachi-27** [hosseinmoein/DataFrame#124]
Nothing very major but I noticed so I am informing you.
So when by default we build our target files using CMakeList.txt all the binary files go into a folder named Bin and for a file name _"_Hello_world" we need a data folder which was available during compile time in test/data/SHORT_IBM.csv but the Hello_World.o file also need that file and folder in the bin while runtime which does not get copied in the required folder.
It is a simple instruction that can be done with little change in CMakeList.txt
Thanks

**Comment by hosseinmoein** [comment]
Thanks for pointing it out. I am on a project for the next week or more. Do you mind doing it and give me a pull request?

Best,
HM

**Comment by hachi-27** [comment]
Yes. I'll but currently, I'm fully jacked up with other things. But do this over the coming weekend.
Thanks

**Comment by NikBomb** [comment]
#133 refers this
