### ISSUE TITLE
write a dataframe failed on Multithreading 

### ISSUE THREAD

**Issue by westfly** [hosseinmoein/DataFrame#126]
1. should write implement on DataFrame Calling SpinLock Guard ?
2. *HeteroVector* hold a global map without an lock,  can this map defined as thread_local(since c++11) while SpinLock also thread_local  too ?
```cpp
struct  HeteroVector  {
...
template<typename T>
inline static std::unordered_map<const HeteroVector *, std::vector<T>>
       vectors_ {  };
...
```

**Comment by hosseinmoein** [comment]
I don't think thread_local is the solution, since the scoping is not going to work and also it would waste/duplicate a big data structure.

Did you declare a global spin lock and did you give it to the DataFrame? Do you have the stack trace from your crash? Do you have any printouts from the crash?
`write()` uses the spin lock, if given, when calling `get_column()`

**Comment by hosseinmoein** [comment]
I'll take a look, when I get a chance. thx

**Comment by westfly** [comment]
I notice that DataFrame copy constructor generate by compiler which marked as *default* while *~DataFrame* has a lock implement.
```cpp
   ...
    DataFrame &operator= (const DataFrame &) = default;
    DataFrame &operator= (DataFrame &&) = default;

    // Because of thread safety, this needs tender loving care
    //
    ~DataFrame();
     ...
```

**Comment by hosseinmoein** [comment]
will take a look

**Comment by hosseinmoein** [comment]
@westfly , I made the copy constructor and assignment operators thread safe.
I still have to look into write(), when I get a chance

**Comment by hosseinmoein** [comment]
@westfly , I tightened the thread locking all around. Please take a look

**Comment by westfly** [comment]
> @westfly , I tightened the thread locking all around. Please take a look

Thx for your reply, I will test on my project asap.
could you make a release tags if it works?
