### ISSUE TITLE
what should I do after cmake in  windows,my ide is visual studio 2012

### ISSUE THREAD

**Issue by Flamealone** [hosseinmoein/DataFrame#13]
what should I do after cmake in  windows,my IDE is visual studio 2012

after cmake，I bulild the dataframe_tester in visual studio 2012,there emergs many errors,I don't know what is happend
1 > -- -- -- -- -- - has started to generate: project: dataframe_tester, configuration: Debug Win32 -- -- -- -- -- -
1 > dataframe_tester. Cc
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview.h (25): error C2873: "value_type" : symbols cannot be used in using declarations
1> c:\users\flame\downloads\dataframe-master\include\ vectorview.h (494): see the reference to instantiating "HMDF ::VectorView" for the class template being compiled
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview.h (26): error C2873: "size_type" : symbol cannot be used in the using declaration
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview.h (27): error C2873: "pointer" : symbol cannot be used in using declaration
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview.h (28): error C2873: "const_pointer" : symbol cannot be used in using declaration
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview.h (29): error C2873: "const_pointer_const" : symbol cannot be used in the using declaration
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview. h(30): error C2873: "reference" : symbol cannot be used in using declaration
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. (before "=")
1>c:\users\ flames \downloads\dataframe-master\include\VectorView. before
1>c:\users\ flames \downloads\dataframe-master\include\ vectorview. h(31): error C2873: "const_reference" : symbol cannot be used in using declaration...........
![image](https://user-images.githubusercontent.com/26116344/54587339-c8547100-4a5a-11e9-94d2-10d958f34352.png)

**Comment by Flamealone** [comment]
Size_type: this symbol cannot be used in the using declaration

**Comment by hosseinmoein** [comment]
On the compile line, define `-DDMS_INCLUDE_SOURCE`
CC @justinjk007

**Comment by Flamealone** [comment]
thank you very much for your answer,but Sorry sir,I don't know what you mean about define -DDMS_INCLUDE_SOURCE,after I intsalled vs2015,I fund one other error as follow,I don't know whether the source also is “define DDMS_INCLUDE_SOURCE”:Severity Code Description Item File Line Prohibit display status
Error (active) Missing parameter list for class template "hmdf::DataFrame" ConsoleApplication1 c:\Users\Flame\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\include\dataframe_functors.h 202

This error seems to come from I don't define DataFrame,but I don't know how can I handle this problem
my project file is 
[ConsoleApplication1.zip](https://github.com/hosseinmoein/DataFrame/files/2983859/ConsoleApplication1.zip)
my build tree like this image:
![image](https://user-images.githubusercontent.com/26116344/54614474-71b95800-4a97-11e9-97dc-4ebc61d24a47.png)

**Comment by justinjk007** [comment]
The project requires C++17. Visual Studio 2017 is *Required*

**Comment by hosseinmoein** [comment]
VS 2017 is required as said above + you must define `DMS_INCLUDE_SOURCE` on the compile line.
In the define section of your project's config, you have to add `DMS_INCLUDE_SOURCE`.
