### ISSUE TITLE
Contribute to DataFrame

### ISSUE THREAD

**Issue by NikBomb** [hosseinmoein/DataFrame#130]

**Comment by hosseinmoein** [comment]
If you would like to contribute to DataFrame, you should get familiarized with the project and its source doe first. I suggest:

1. Read the documentation from beginning to end
2. Get comfortable with compiling the project
2. Go through the _Hello World_
3. Understand the `Vectors` code
3. Go through the other test programs along with most of the _features_ in the documentation
4. Contribute + document + write test case
