### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by adeolaibigbemi** [hosseinmoein/DataFrame#131]
I want to contribute to this project.
Kindly reach out to me.

**Comment by hosseinmoein** [comment]
Read #130 issue

**Comment by hosseinmoein** [comment]
If you have noticed in most DataFrame member functions, the programmer must specify the column type(s). In some cases, this is not necessary. We could deduce the column type(s) from other parameters passed to the function. An example is the `load_column()` member function.

As the first contribution, why don't you change `load_column()` not to require column type and become a non-template member function. You can figure out the type of the column from the type of the data passed to it
