### ISSUE TITLE
Multiple groupby condition problem

### ISSUE THREAD

**Issue by Nancyzxy** [hosseinmoein/DataFrame#136]
With your groupby function,I need to specifiy the triples to aggregate the data. But what if I don't know the aggregating types until I get data? I mean I need to judge the type and genenrate the tuple, but when writing the function, I don't know this. Do I need to judge every condition ? It seems too complex....

**Comment by hosseinmoein** [comment]
I don’t think I understand the issue. If you have loaded the data, you should know the nature of the data
Could you explain through an actual example. Maybe I can suggest something
