### ISSUE TITLE
Example file not compiling

### ISSUE THREAD

**Issue by verybadcoder01** [hosseinmoein/DataFrame#141]
I tried running file "dataframe_perfomance" but here what I got:
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `hmdf::HeteroVector::~HeteroVector()':
/usr/local/include/DataFrame/Vectors/HeteroVector.h:54: undefined reference to `hmdf::HeteroVector::clear()'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `hmdf::operator<(hmdf::DateTime const&, hmdf::DateTime const&)':
/usr/local/include/DataFrame/Utils/DateTime.h:495: undefined reference to `hmdf::DateTime::compare(hmdf::DateTime const&) const'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `hmdf::DataFrame<long, hmdf::HeteroVector>::gen_datetime_index(char const*, char const*, hmdf::time_frequency, long, hmdf::DT_TIME_ZONE)':
/usr/local/include/DataFrame/Internals/DataFrame_set.tcc:241: undefined reference to `hmdf::DateTime::DateTime(char const*, hmdf::DT_DATE_STYLE, hmdf::DT_TIME_ZONE)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_set.tcc:243: undefined reference to `hmdf::DateTime::DateTime(char const*, hmdf::DT_DATE_STYLE, hmdf::DT_TIME_ZONE)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_set.tcc:244: undefined reference to `hmdf::DateTime::diff_seconds(hmdf::DateTime const&) const'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `void hmdf::_generate_ts_index_<long>(std::vector<long, std::allocator<long> >&, hmdf::DateTime&, hmdf::time_frequency, long)':
/usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:834: undefined reference to `hmdf::DateTime::date() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:835: undefined reference to `hmdf::DateTime::add_years(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:838: undefined reference to `hmdf::DateTime::date() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:839: undefined reference to `hmdf::DateTime::add_months(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:842: undefined reference to `hmdf::DateTime::date() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:843: undefined reference to `hmdf::DateTime::add_days(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:846: undefined reference to `hmdf::DateTime::date() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:847: undefined reference to `hmdf::DateTime::add_days(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:850: undefined reference to `hmdf::DateTime::time() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:851: undefined reference to `hmdf::DateTime::add_seconds(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:854: undefined reference to `hmdf::DateTime::time() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:855: undefined reference to `hmdf::DateTime::add_seconds(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:858: undefined reference to `hmdf::DateTime::time() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:859: undefined reference to `hmdf::DateTime::add_seconds(long)'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:862: undefined reference to `hmdf::DateTime::long_time() const'
/usr/bin/ld: /usr/local/include/DataFrame/Internals/DataFrame_standalone.tcc:863: undefined reference to `hmdf::DateTime::add_nanoseconds(long)'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `std::vector<double, std::allocator<double> >& hmdf::DataFrame<long, hmdf::HeteroVector>::create_column<double>(char const*)':
/usr/local/include/DataFrame/Internals/DataFrame_set.tcc:58: undefined reference to `hmdf::HeteroVector::HeteroVector()'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `void __gnu_cxx::new_allocator<hmdf::HeteroVector>::construct<hmdf::HeteroVector, hmdf::HeteroVector>(hmdf::HeteroVector*, hmdf::HeteroVector&&)':
/usr/include/c++/9/ext/new_allocator.h:147: undefined reference to `hmdf::HeteroVector::HeteroVector(hmdf::HeteroVector&&)'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `void std::_Construct<hmdf::HeteroVector, hmdf::HeteroVector const&>(hmdf::HeteroVector*, hmdf::HeteroVector const&)':
/usr/include/c++/9/bits/stl_construct.h:75: undefined reference to `hmdf::HeteroVector::HeteroVector(hmdf::HeteroVector const&)'
/usr/bin/ld: CMakeFiles/DeepM.dir/main.cpp.o: in function `std::thread::thread<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<hmdf::MeanVisitor<double, long>& (hmdf::DataFrame<long, hmdf::HeteroVector>::*)(char const*, hmdf::MeanVisitor<double, long>&, bool), hmdf::DataFrame<long, hmdf::HeteroVector>*, char const*, std::reference_wrapper<hmdf::MeanVisitor<double, long> >, bool> >, hmdf::MeanVisitor<double, long>&>::_Async_state_impl(std::thread::_Invoker<std::tuple<hmdf::MeanVisitor<double, long>& (hmdf::DataFrame<long, hmdf::HeteroVector>::*)(char const*, hmdf::MeanVisitor<double, long>&, bool), hmdf::DataFrame<long, hmdf::HeteroVector>*, char const*, std::reference_wrapper<hmdf::MeanVisitor<double, long> >, bool> >&&)::{lambda()#1}, , void>(std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<hmdf::MeanVisitor<double, long>& (hmdf::DataFrame<long, hmdf::HeteroVector>::*)(char const*, hmdf::MeanVisitor<double, long>&, bool), hmdf::DataFrame<long, hmdf::HeteroVector>*, char const*, std::reference_wrapper<hmdf::MeanVisitor<double, long> >, bool> >, hmdf::MeanVisitor<double, long>&>::_Async_state_impl(std::thread::_Invoker<std::tuple<hmdf::MeanVisitor<double, long>& (hmdf::DataFrame<long, hmdf::HeteroVector>::*)(char const*, hmdf::MeanVisitor<double, long>&, bool), hmdf::DataFrame<long, hmdf::HeteroVector>*, char const*, std::reference_wrapper<hmdf::MeanVisitor<double, long> >, bool> >&&)::{lambda()#1}&&)':
/usr/include/c++/9/thread:126: undefined reference to `pthread_create'

**Comment by hosseinmoein** [comment]
DataFrame is _almost_ a header-only library. You must compile and archive the DataFrame library first. Then link your executable with that library. If you follow the build instructions (or duplicate the CMake file) in README, it should work
