### ISSUE TITLE
how to pass extra parameters in functor wheu using get_data_by_sel ?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#142]
Here is a piece of code from hello_world.cc:
`auto    functor =
        [](const std::string &, const double &val)-> bool { return (val > 150.0); };  `
`auto    above_150_df =
       ibm_df.get_data_by_sel<double, decltype(functor), double, long>("IBM_Close", functor);`

I want to pass a value to functor rather than using 'val>150' in the functor, like:
`auto    functor =
        [](const std::string &, const double &val, double number)-> bool { return (val > number); };`

Then how to call get_data_by_sel if I use the functor above?

I tried:
`double num_tmp = 200.0;`
`auto    functor =
        [](const std::string &, const double &val, double number)-> bool { return (val > number); };`
`auto    above_150_df =
       ibm_df.get_data_by_sel<double, double, decltype(functor), double, long>("IBM_Close",num_tmp, functor);`

but it does not work.
Is it possible to use a functor above if I use get_data_by_sel  ?

Thank you very much.

**Comment by yuxiaojian01** [comment]
I can use another way to solve this problem:
double num_tmp = 200.0;
auto functor = [&](const std::string &, const double &val)-> bool { return (val > num_tmp); };
auto above_150_df = ibm_df.get_data_by_sel<double, decltype(functor), double, long>("IBM_Close", functor);

Please delete this issue.

**Comment by hosseinmoein** [comment]
First, the callback in hello_world.cc is called a lambda not a functor.
You can do what you want in a couple of different ways:

You can capture the externally declared number in your lambda and use it, similar to your solution:
```
double num_tmp = 200.0;
auto functor = [num_tmp](const std::string &, const double &val)-> bool { return (val > num_tmp); };
```


Or you could declare a functor class and pass it as callback instead of the lambda. This way you could maintain more complicated state inside your functor class
```
struct MyClass. {

    bool operator()(const std::string &, const double &val)  { return (val > number); }

private:

    double number { 200.0 }; 
};
```

**Comment by yuxiaojian01** [comment]
Thank you very much. Your second solution is really good!!
