### ISSUE TITLE
Does get_view_by_sel only work under C++ 20?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#143]
I run this code:
`auto    above_150_view =
            ibm_df.get_view_by_sel<double, decltype(functor), double, long>("IBM_Close", functor); `

under C++ 17, and the program stopped.
When I run the above code under C++ 20, it worked.
Does it mean get_view_by_sel only work under C++20 ?

**Comment by yuxiaojian01** [comment]
In addition, I changed C++ standard to  C++20, it worked, but when I compiled the project, it has two "runtime_error", in:
1) HeteroPtrView.tcc line 95, get_vector() function:
   ` if (iter == views_<T>.end())`
        `throw std::runtime_error("HeteroPtrView::get_vector(): ERROR: "`
                                ` "Cannot find view");`

2) HeteroView.tcc line 72, get_vector() function:
`if (iter == views_<T>.end())`
        `throw std::runtime_error("HeteroView::get_vector(): ERROR: "`
                                ` "Cannot find view");`

I added " #include <stdexcept> " to the above two files, it worked.
I am not sure whether these two files missed two "includes" or, it just because of my IDE? (I used VS 2019).

**Comment by hosseinmoein** [comment]
This is probably specific to the compiler and the version you are using. I cannot reproduce this on my side with gcc or clang
Try using a different version of your compiler.

What does `adding #include` mean exactly? What `#include`s did you add

**Comment by yuxiaojian01** [comment]
I added ` #include <stdexcept>`  to the two files above.  Sorry about missing `<stdexcept>`.  The editor ignored <> when editing.

**Comment by hosseinmoein** [comment]
Not a bad idea to add it anyway. I will add it in a couple of days
