### ISSUE TITLE
KthValueVisitor doesn't handle 0th value

### ISSUE THREAD

**Issue by edouardberthe** [hosseinmoein/DataFrame#145]
Hello, 

Is there any specific reason why the `KthValueVisitor` doesn't handle finding the 0th (first) value here? 

https://github.com/hosseinmoein/DataFrame/blob/9c7e2254162b209f3190bfc7e763a985563f4fb4/include/DataFrame/DataFrameStatsVisitors.h#L2026

I found it problematic when wanting to find a, e.g. 5% quantile on a vector constituted of few values (let's say 10), as it may fall between the first and second one.
The `QuantileVisitor` calls the `KthValueVisitor` with `k = 0` which seems to fail.

Thanks,
Edouard

**Comment by hosseinmoein** [comment]
`KthValueVisitor` cannot accept 0 because of the way it is coded. So, the first value would be _k == 1_.
But there might be a problem in `QuantileVisitor` which should not call `KthValueVisitor` with _k == 0_.

Can you give me sample data and how you call the visitor to reproduce this?
