### ISSUE TITLE
Can I use function get_data_by_sel to select data by index?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#146]
Hi, I want to ask if I can use get_data_by_sel to select data by index ? According to the documentation, it seems get_data_by_sel can only select data by column names.
I tried:
`auto functor=`
            `[](const std::string& , const double& close,, const std::string& idx) -> bool {return ((close > 100.0) && (idx.find(".SSS")!=std::string::npos )); }; //idx is the column of index`

`StrDataFrame df_s = df.get_data_by_sel<double,std::string, decltype(functor),double, std::string>("closeable",DF_INDEX_COL_NAME, functor);`

Is there something wrong with my code (maybe index name is not DF_INDEX_COL_NAME)? or get_data_by_sel  does not support select data by index?

I don't use get_data_by_idx because I want to select data by both index and other columns together.
    
Thank you very much.

**Comment by hosseinmoein** [comment]
In all the callbacks in data selections and visitors, the first parameter is always the index:


auto functor =
[](`const std::string &idx` , const double &close) -> bool {return ((close > 100.0) && (idx.find(".SSS")!=std::string::npos )); };

**Comment by yuxiaojian01** [comment]
Got it. Thank you.

**Comment by yuxiaojian01** [comment]
Another question, what if only select data by index? 
I tried the following code, but it can't compile.
`auto func_buy_r =
        [](const std::string& idx) -> bool {return (idx.find(".SSS") != std::string::npos); };`
`df= df.get_data_by_sel<std::string,decltype(func_buy_r), double, std::string>(DF_INDEX_COL_NAME,func_buy_r);`

and also:
`df = df.get_data_by_sel<decltype(func_buy_r), double, std::string>(func_buy_r);`

Do you have any idea of only selecting by index?

Thank you.

**Comment by hosseinmoein** [comment]
You can use the `get_data_by_sel()` and just ignore the column parameter, just select on the index parameter
