### ISSUE TITLE
How to get multiple columns from a dataframe, and return a new dataframe?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#147]
I want to get only several columns from a dataframe, similar to python: 
`df[[col1, col2,col3]]`

I can only see get_column() function in the doc, which only get single column from a dataframe.
Does it support to get multiple columns from a dataframe, and return a new dataframe?

Thank you very much.

**Comment by hosseinmoein** [comment]
Currently I don't have this method. I may add it in the future.
But there are a few ways you can do this:
1. You can just assign your df to another df and drop the column(s) you don't need.
2. Use the `get_data_by_sel(()` method on the columns you need and in the callback always return true.
3. Declare an empty df and manually add index and columns by calling the `get_index()` and `get_column()` methods on the source df.

**Comment by yuxiaojian01** [comment]
Thank you.

**Comment by hosseinmoein** [comment]
I just implemented `get_data()` and `get_view()` that returns a another DataFrame/view for a given set of columns and the index.
