### ISSUE TITLE
padding policy of load_column function?

### ISSUE THREAD

**Issue by yuxiaojian01** [hosseinmoein/DataFrame#148]
Hi, when I test load_column function with a default padding_with_nans policy, I find:
std::string type: padding with "",
int type: padding with 0 (rather than std::numeric_limits<int>::quiet_NaN),
double type: padding with std::nan.

Am I correct? Do you have a list of default padding values of different data type when using load_column()?

Thank you.

**Comment by hosseinmoein** [comment]
The logic is
```
if std::numeric_limits<T>::has_quiet_NaN is true:
    get (std::numeric_limits<T>::quiet_NaN())
else:
    get (<default value of type T>)
```

See `https://en.cppreference.com/w/cpp/types/numeric_limits/has_quiet_NaN` for further info

**Comment by yuxiaojian01** [comment]
Thank you!
