### ISSUE TITLE
asynchronously run program

### ISSUE THREAD

**Issue by BCSN000001** [hosseinmoein/DataFrame#149]
Hi hossein，

In recent days, I am using this library asynchronously. 
My code is like below: 

template\<typename I>
	DataTable<I>::DataTable(
		hmdf::StdDataFrame\<IndexType>&& df,
		const Dictionary<std::string, std::pair<std::string, bool>>& col_types,
		const bool indices_in_ascending_order,
		const bool only_optionaled_value)
	{
		**_df = df;**
		_col_types = col_types;
		_indices_in_ascending_order = indices_in_ascending_order;
		_only_optional_value = only_optionaled_value;
	}

when executing _df = df,  it throws errors as 

‘’Exception thrown at 0x000001B3209307A0 in run_scheduler.exe: 0xC0000005: Access violation executing location 0x000001B3209307A0.“ when calling function 

HeteroVector &HeteroVector::operator= (const HeteroVector &rhs)  {
    if (&rhs != this)  {
        clear();
        clear_functions_ = rhs.clear_functions_;
        copy_functions_ = rhs.copy_functions_;
        move_functions_ = rhs.move_functions_;

        for (auto &&copy_function : copy_functions_)
            **copy_function(rhs, *this);**
    }

    return (*this);
}

![image](https://user-images.githubusercontent.com/45456983/146577207-116be57e-3761-462d-91d3-acb6c5040b49.png)

This error only occurs when call the function asynchronously. 
While it works synchronously.

**Comment by hosseinmoein** [comment]
I _think_ this is the problem:
You are passing `df` as rvalue reference, so you need to change to this line
```
_df = std::move(df);
```

And you have to realize that after this line, `df` will be empty
