### ISSUE TITLE
Questions about using the libDataSci.a in Ubuntu?

### ISSUE THREAD

**Issue by raincls** [hosseinmoein/DataFrame#15]
Thank you for implementing such a powerful tool.

I successfully compiled and ran the test on ubuntu 18.04.2，and  libDataSci.a  generated in the folder Linux.GCC64 and Linux.GCC64D.

But I don't know how to use this static library.
I tried to copy the header files in include folder and libDataSci.a to the same folder,
create a new .c file, #include "DataFrame.h", and trying to run the example code at the project homepage.
I used the g++ compiler and the comand is 
"g++ testDF.c -L. -lDataSci".

the output message is 
"testDF.c: In function ‘int main(int, char**)’:
testDF.c:13:9: error: ‘DataFrame’ does not name a type
 typedef DataFrame<unsigned long, std::vector> MyDataFrame;
         ^~~~~~~~~
......
"
seem like I did not use the libDataSci.a correctly.

Could you please add some more basic using instructions in the tutorial for the people who are not familiar with C++ and Linux?

Thanks for your time.

**Comment by hosseinmoein** [comment]
follow the structure for compiling and coding in `Makefile.Linux.GCC64D` and `dataframe_tester.cc` files.
In your particular case it seems you maybe missing two things
1) On your compile line you need a `-I` to locate the include directory.
2) In your C++ source file you need namespace similar to `dataframe_tester.cc`.
On top of the file you need 
```
using namespace hmdf;
```
or alternatively:
```
typedef hmdf::DataFrame<unsigned long, std::vector> MyDataFrame;
```

**Comment by raincls** [comment]
Thank you for your kind reply.
I find out I am using the lib incorrectly. 
There seems still a small problem, I can not read data from CSV files(shown in the output of dataframe_tester.cc), and is there a way to save dataframe to a CSV file?

**Comment by hosseinmoein** [comment]
In the test file the location of the CSV files are hardcoded to be the `current directory`.
So copy the CSV files from the `test` directory to whatever directory you are running the test from.

**Comment by Rhysoshea** [comment]
@hosseinmoein I had an issue in-line with the above:

>  error: ‘DataFrame’ does not name a type

After following your recommendation I was then faced with a new error:

> error: type/value mismatch at argument 2 in template parameter list for ‘template<class I, class H> class hmdf::DataFrame’
>  typedef hmdf::DataFrame<unsigned long, std::vector> MyDataFrame;

Looking into the header files I found that the DataFrame class is hardcoded to receive a HeteroVector as the second argument which is a value type

> class DataFrame : public ThreadGranularity  {
> static_assert(std::is_base_of<HeteroVector, H>::value ||
>                       std::is_base_of<HeteroView, H>::value,
>                   "H argument can only be either of "
>                   "HeteroVector or HeteroView or their derived types");
>

So changing the code given in the example for defining a DataFrame:

> typedef hmdf::DataFrame<unsigned long, hmdf::HeteroVector>	MyDataFrame;

Now compiles without error. Is there something I am missing or have the header files been changed and the documentation out of date maybe?
Thanks

**Comment by hosseinmoein** [comment]
Yes, the code was changed a few month back when I introduced views.
Also the name of the library was changed to `libDataFrame.a`

I have two convenient typedef's in `DataFrame.h` file that you can use:
```
template<typename I>
using StdDataFrame = DataFrame<I, HeteroVector>;

template<typename I>
using DataFrameView = DataFrame<I, HeteroView>;
```

Thanks for pointing out the documentation being outdated. I just fixed it.
