### ISSUE TITLE
Help wanted ( question)

### ISSUE THREAD

**Issue by jithin917** [hosseinmoein/DataFrame#150]
Is there a way to resample time series data with this library? Something like pandas resample. ? 
And where() 

How to populate dataframe from json format which is received from network socket. I am using qt for network request.

**Comment by hosseinmoein** [comment]
Please see the documentation. There are several `get_data_<...>()` and `get_view_<...>()` functions that resample the data in different ways. If you mean resampling by time frequency, I don't have that yet but planning to add it. But you can also look at `bucketize()`.

Yes, DataFrame supports reading and writing data a JSON format. Please see documentation for `read()` and `write()`.

Let me know if this works out for you

**Comment by jithin917** [comment]
Sure sir. I will try it out and let you know.

Thank you for your kind support..
Regards
Jithin Mohan
