### ISSUE TITLE
Is this compatible for c++11 or c++14?

### ISSUE THREAD

**Issue by xkungfu** [hosseinmoein/DataFrame#151]
for my old code only running in c++11 and c++14, I have a question about this.
can this compile in c++11 or c++14?

thanks!

**Comment by hosseinmoein** [comment]
DataFrame requires at least a C++17 compliant, 64bit compiler to compile and work properly.
If you already have code that you compile with C++14, then upgrading to C++17 should be easy.

**Comment by xkungfu** [comment]
I see, thank you!
