### ISSUE TITLE
Is there any plan to add data adapter for csv or some database? 

### ISSUE THREAD

**Issue by bwlee** [hosseinmoein/DataFrame#16]
Hi, thanks for share your great code,  I am really impressed with the  precision of date time supported, which is much better than pandas.

Is there any plan to add any adapters to import data from csv file or some database?

this should be tagged as a feature request, but sorry for cannot do it.

**Comment by hosseinmoein** [comment]
There are already methods for reading and writing CSV files
```
read()
read_async()
write()
write_async()
```

Please see the documentation and the test file

**Comment by hosseinmoein** [comment]
Let me know, if anything is still unclear

**Comment by bwlee** [comment]
Thanks!
I have found the CSV files supported but with a special format to include column type info, and I think it may be better if can read a normal CSV file with specified types for columns,  the given special format may have limits when importing data with a huge row number.

BTW,  I want to know whether is it possible to allow users write adapters to read database directly, like pandas which can access MYSQL, sqlite, or hdf5 file.  

Thanks again for your sharing!

**Comment by hosseinmoein** [comment]
I don't believe the current csv format creates any problem for large data sets. The type specification is repeated per row only once. So for a huge row there is only a few bytes of extra info.
Furthermore, if you already have an existing csv file, you can add the extra info by hand to it. It is that simple and it meant to be that way.

Regarding contributions to the project, I welcome all contributions. Please read the `contribute` section of readme. And when you are done and tested the code, you can send me a `Pull Request`.
