### ISSUE TITLE
DateTime: Definition of templated function member date_to_str is not in the header

### ISSUE THREAD

**Issue by SpaceIm** [hosseinmoein/DataFrame#163]
It doesn't fail when DataFrame & tests are compiled because date_to_str() is used only in DateTime.cc compilation unit where it is also defined.

However, date_to_str() is publicly exposed in DateTime header, but it can't work in any other context than DateTime.cc compilation.

It should probably be removed, and its definition moved to string_format() in DateTime.cc, which is the only user of this function.

**Comment by hosseinmoein** [comment]
This has been fixed in master
Thx
