### ISSUE TITLE
about date or datetime column

### ISSUE THREAD

**Issue by xkungfu** [hosseinmoein/DataFrame#164]
1.` df.create_column<DateTime>("xxx") `seems not work. It seems there isn't a column type of date object or datetime object, isn't it ?
2. so, how to filter, sort, compare by a date string column? such as: {"2022-01-01", "2022-02-02",  ... }
   
on solution is using int column instead of string column?  converting date string to int first.  such as: {"1640966400", "1641052800,  ... } 

is there a better way?

**Comment by hosseinmoein** [comment]
1. What do you mean by it doesn't work -- it should work? What happens?
2. If the type is DateTime, then sorting will work properly. If it is simply a string of some format, then the sorting has to be customized
3. Using an integer type for a date is more efficient space-wise and it is more efficient with some algorithms. But some algorithm may need specialized date/time manipulation which would be more involved with an integer type date. So, it really depends on you and your application

**Comment by xkungfu** [comment]
thank you,!
I will test it again to find what is wrong in my codes. report later.

**Comment by xkungfu** [comment]
TEST CODES:
```
    ULDataFrame         df;
    df.create_column<std::string>("date_str");
    df.create_column<DateTime>("date_obj");

    std::cout << "[test_dataframe_generate2] df 1: ";
    df.write<std::ostream, std::string, double>(std::cout, io_format::csv2);

    df.append_index(0);

    const char* d1 = "2022-01-21";
    df.append_column("date_str", d1);

    DateTime dtobj("2022-01-22", hmdf::DT_DATE_STYLE::ISO_STYLE);
    std::cout << "[test_dataframe_generate2] dtobj 1: "  << dtobj.string_format (DT_FORMAT::ISO_DT) << std::endl; //2022-01-22
    df.append_column("date_obj", dtobj);

    std::cout << "[test_dataframe_generate2] df 2: ";
    df.write<std::ostream, std::string, double>(std::cout, io_format::csv2);


    std::vector dtobj_vec = df.get_column<DateTime>("date_obj");
    std::cout << "[test_dataframe_generate2] dtobj 2: "  << dtobj_vec[0].string_format (DT_FORMAT::ISO_DT) << std::endl; //2022-01-22

```

OUTPUT:
```
[test_dataframe_generate2] df 1: INDEX:0:<ulong>,date_str:0:<string>,

[test_dataframe_generate2] dtobj 1:2022-01-22
[test_dataframe_generate2] df 2: INDEX:1:<ulong>,date_str:0:<string>,
0,,

[test_dataframe_generate2] dtobj 2:2022-01-22


```
sorry, sure it is my mistake.
I added some codes about get and output column, after this I saw the date.
before this, it didn't show the date_obj column in ostream.

**Comment by xkungfu** [comment]
It is a little difficult to read doc because I am poor in English. I learn via examples usually.
I will take more time to study.
thank you very much!
