### ISSUE TITLE
how to write get_data_by_sel in one line?

### ISSUE THREAD

**Issue by xkungfu** [hosseinmoein/DataFrame#168]
```
    std::cout << "\nTesting get_data_by_sel() ..." << std::endl;

    std::vector<unsigned long>  idx = { 123450, 123451, 123452, 123453, 123454, 123455, 123456 };
    std::vector<double> d1 = { 1, 2, 3, 4, 5, 6, 7 };
    std::vector<double> d2 = { 8, 9, 10, 11, 12, 13, 14 };
    std::vector<double> d3 = { 15, 16, 17, 18, 19, 20, 21 };
    std::vector<double> d4 = { 22, 23, 24, 25 };
    std::vector<std::string> s1 = { "11", "22", "33", "ee", "ff", "gg", "ll" };
    MyDataFrame         df;

    df.load_data(std::move(idx),
                 std::make_pair("col_1", d1),
                 std::make_pair("col_2", d2),
                 std::make_pair("col_3", d3),
                 std::make_pair("col_str", s1));
    df.load_column("col_4", std::move(d4), nan_policy::dont_pad_with_nans);

    auto    functor =
        [](const unsigned long &, const double &val)-> bool { return (val >= 5); };
    auto    result =
        df.get_data_by_sel<double, decltype(functor), double, std::string>("col_1", functor);
```
how to merge the codes about selecting to one line like below?

`auto result =  df.get_data_by_sel<double, std::string>("col_1", [](const unsigned long &, const double &val)-> bool { return (val >= 5); });
`

**Comment by hosseinmoein** [comment]
Your one-liner looks good. The only thing is you are not specifying all the required types in the template type list. C++ is a statically typed language, so all types must be known at compile Time.
So you need this:
```
df.get_data_by_sel<double, decltype(functor), double, std::string>("col_1", [](const unsigned long &, const double &val)-> bool { return (val >= 5); });
```

Again, without reading the document you are going to have hard time making this work

**Comment by xkungfu** [comment]
thank you!
I think "decltype(functor)" would trigger error: "undeclared identifier 'functor'". how to remove or modify it?

**Comment by hosseinmoein** [comment]
typedef it in advance.
In the first place, why do you need to this in one line?

**Comment by xkungfu** [comment]
"get_data_by_sel" is a common function often to use , so the codes would be not pretty if use it too many times.
I just want know if there is a way to merge to one line. It is not necessary. you would continue to do the more important work than it.
