### ISSUE TITLE
about get last row and get_data_by_loc

### ISSUE THREAD

**Issue by xkungfu** [hosseinmoein/DataFrame#171]
in pandas , df.iloc[-1] will get the last row.
when I use get_data_by_idx, the range can't be set to negative.
and when use get_data_by_loc {-1}, the application throw error: DataFrame::get_data_by_loc(): ERROR: Bad begin, end range: 64, 0
and when use get_data_by_loc {-10, -1} , the last row not in result.

so, can you set "-1" to last row?

**Comment by xkungfu** [comment]
according to the doc, I saw the last row is not in range -1.
did I miss something?

the doc:
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/get_data_by_loc.html

`MyDataFrame df4 = df.get_data_by_loc<double>(Index2D<long> { -4, -1 });
`
the output of df4 is:
```
df4: 
INDEX:3:<ulong>:123450,123455,123450,
col_1:3:<double>:4,5,6,
col_2:3:<double>:11,12,13,
col_3:3:<double>:18,19,20,
col_4:3:<double>:25,nan,nan,
```

but the last row is: "123449 7 14 21 nan"

does  the row we talk about is the same row about the last row?

**Comment by hosseinmoein** [comment]
I will take a look

**Comment by hosseinmoein** [comment]
I found the problem. I will fix it over the weekend

**Comment by hosseinmoein** [comment]
@xkungfu , the fix is released to master
