### ISSUE TITLE
Can provide a function to query the column index from the column name

### ISSUE THREAD

**Issue by czyt1988** [hosseinmoein/DataFrame#177]
Can provide a function to query the column index from the column name? 
Because I found that some functions will change the original index of the column, such as rename_column,retype_column,consolidate,self_shift etc. On some occasions, I get the column through the column index, but I find that after calling the rename_column function, the index of the original column becomes the last, so I hope there is a method to get the column index corresponding to the column name.

**Comment by hosseinmoein** [comment]
I don't have those methods yet. accessing by name was always the primary method of accessing columns, so I didn't put a lot of emphases on accessing by index.
But, I can add those methods sometimes over the weekend

**Comment by hosseinmoein** [comment]
@czyt1988 ,

This has been implemented in master
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/col_name_to_idx.html

**Comment by czyt1988** [comment]
Thank you very much
