### ISSUE TITLE
[Feature Request] to_eigen() that convert numeric columns to eigen matrix.

### ISSUE THREAD

**Issue by kilasuelika** [hosseinmoein/DataFrame#179]
`Eigen` is heavily used in numeric analysis applications. If there is a `to_eigen()` method then it will be much easier to do analysis.

I use `Eigen` for some years and can provide some contributes.

**Comment by hosseinmoein** [comment]
That's a good point and I think it would be very helpful. But `to_eigen()` is a simple function to write and any DataFrame user could write it.

One of the principles I have followed in this library is that DataFrame should only depend on C++ language and its standard library. I don't want to break that principles
