### ISSUE TITLE
Help, c++ syntax.

### ISSUE THREAD

**Issue by yssource** [hosseinmoein/DataFrame#18]
``` C++
    // (..., visit_impl_help_<std::decay_t<T>, TYPES>(visitor)); // C++17
    using expander = int[];
    (void) expander { 0, (visit_impl_help_<T, TYPES>(visitor), 0) ... };

```

I got confused by the syntax. I think you are using the list initialization, But I don't understand what `(void)` is for here? 

It is equal to this, isn't it?
`int v[] = { 0, (visit_impl_help_<T, TYPES>(visitor), 0) ... };`

Although this is not a proper place to ask the question, I google and stackoverflow a lot, and still got confused about it.

Thank you in advance.

**Comment by hosseinmoein** [comment]
I have no idea why I have a `(void)` there :-)
It is completely unnecessary

**Comment by yssource** [comment]
I assume the real thing you ware trying to do is `visit_impl_help_<T, TYPES>(visitor)`.
But I got confused what is for here `(void) expander { 0, (visit_impl_help_<T, TYPES>(visitor), 0) ... };`.
It seems it is a bit complicated and difficult to understand.

**Comment by hosseinmoein** [comment]
no wait, I think there is a misunderstanding

This `expander { 0, (visit_impl_help_<T, TYPES>(visitor), 0) ... };` is necessary to generate a list of all necessary visitor types.

This `(void)` is not necessary

**Comment by hosseinmoein** [comment]
Now I remember why I had `(void)`. Some compilers (e.g. gcc) need that, otherwise they generate a ton of warnings about unused expansion list.
So the whole thing is necessary

**Comment by yssource** [comment]
Thank you so much.

I'v found a good explanation about it.

[Variadic expander without a typedef](https://stackoverflow.com/questions/35233624/variadic-expander-without-a-typedef)

[Variadic template pack expansion](https://stackoverflow.com/questions/25680461/variadic-template-pack-expansion/25683817)
