### ISSUE TITLE
[Feature Request] Automatic columns detection for read().

### ISSUE THREAD

**Issue by kilasuelika** [hosseinmoein/DataFrame#180]
I suggest provide a new `normal_csv` format  that the column type is automatically detected. Use a two-pass procedure. First read some initial rows to decide column type and then the second pass to read values.

The current `csv` and `csv2` format is rarelly used and inconvenient.

**Comment by kilasuelika** [comment]
Deciding column types for `string`, `int` and `double` are easy but for datetime it will be very difficult.

**Comment by hosseinmoein** [comment]
Even auto-detecting between int and double is not that simple. Imagine if a few first items of a double column happen to be integers. Or if the data by nature is integer but the user wants to have a double column for calculation purposes. For example, _number of shares_ traded is an integer value by nature. But most often it is stored as a floating point because the column is involved in calculations and comparisons with other floating point figures.

**Comment by kilasuelika** [comment]
> Even auto-detecting between int and double is not that simple. Imagine if a few first items of a double column happen to be integers. Or if the data by nature is integer but the user wants to have a double column for calculation purposes. For example, _number of shares_ traded is an integer value by nature. But most often it is stored as a floating point because the column is involved in calculations and comparisons with other floating point figures.

When I tried to implement one, I encounter a problem. It looks like that `HeteroVector` doesn't store type information. If there are 1000 columns, how can the user specify them one by one?

**Comment by hosseinmoein** [comment]
In C++ you can not `store` type information. C++ is a statically typed language

**Comment by hosseinmoein** [comment]
when you write the data in DataFrame by using the `write()` function, it will store all the info in needs to read it back.
Also, the same thing is `to_string()` and `from_string()`

**Comment by kilasuelika** [comment]
After some research, I decided to write my own DataFrame library. You can check it on [DataFrameCpp](https://github.com/kilasuelika/DataFrameCpp.git)
