### ISSUE TITLE
Arm64 support?

### ISSUE THREAD

**Issue by Sr-316** [hosseinmoein/DataFrame#182]
Does this library compile and run on macOS Monterey 12.5 ARM64 ??? I'm simply trying to run the examples using g++ (/usr/bin/g++) - std=c++20 and its saying it won't run on this architecture... I tried to download it and run it off of vcpkg, and tried building and installing from source and neither has worked... is there specific compile  and/or linking flags to use? It's seeming like there's a lot of packages in c++ that don't run with the arm64/ aarch64 architecture... I just purchased this Mac and was excited to get programming on it after always thinking everything ran smoother on Mac's lol

Am I missing something here? (Please god tell me I am)

**Comment by hosseinmoein** [comment]
I also have a MacBook but with Intel chip. I have never worked with a Mac with arm chip.
When you say it doesn't work what do you exactly mean?
Does it compile? If not what compile errors do you get?
If it compiles, what runtime errors do you get?

**Comment by hosseinmoein** [comment]
Also try Conan
https://conan.io/center/dataframe?os=Linux&tab=overview

**Comment by Sr-316** [comment]
![DataFrameError](https://user-images.githubusercontent.com/102568626/172390578-8ad89a50-fb5a-4bfa-8146-1762fd33b096.png)

**Comment by Sr-316** [comment]
linker error obviously but.. I have the project cloned project directories include folder and added it all to CMakeLists.txt (will post a pic of that)

**Comment by hosseinmoein** [comment]
Two guess:
DataFrame is _almost_ a header-only library. But it is not, you have to first build the DataFrame library and then link with it.
So my first guess is that you are not building the DataFrame library.
My second guess is that you may have path problems in your linker. You should point the linker to the place where DataFrame library is with `-L` linker command line

**Comment by hosseinmoein** [comment]
yes. The one with `D` is the debug version

**Comment by hosseinmoein** [comment]
it should

**Comment by Sr-316** [comment]
beautiful! thank you sir.. it didn't work at first try on command line because I hadn't copied the data files to the root project dir then I went to the examples folder and jus tried it on the hello_world provided there and it didn't see the data files so I moved the data folder to the root directory and tried the "main" again and it worked.

**Comment by Sr-316** [comment]
Hey, I'm working on a personal project, taking Interactive Brokers C++ TWS API and trying to recreate some projects I've made in Python, in C++ (and am aiming to utilize async functionality of C++) .

In Python, Dictionaries are perfect containers (storage objects) for financial purposes and work seamlessly with pandas DataFrames.. I was hoping to use the same concept with C++ and cpp DataFrames. Are MultiMaps easy to use with these DataFrames.. 

Do you have any messenger app (e.g. Telegram or What'sApp) that we could maybe chat on a bit?

I'm currently building automated Options trading strategies in C++ (sort of recreating them, from Python versions I have already coded up)..

My story is pretty crazy, I've taught myself programming in like 5 Dif languages and learned most assets/facets of the financial markets (as far as technical analysis trading) and mixing the 2.. in the past 2 years...... was homeless with my son about 5 years ago and forced to find a new line of work due to a 2nd spine surgery.. so.. here I am..

But yea...  regardless... Thank you very much for your time.. for your rapid responses on earlier messages, and your time/work provided to the open source community.. soon as I get this work up and going I'll definitely be a sponsor..

**Comment by hosseinmoein** [comment]
DataFrame is kind of like a multimap with an analytical interface. You can use either/or DataFrame and/or multimap.
But you should understand that neither of them is multithreaded safe. Read the multithreading section of DataFrame doc

**Comment by Sr-316** [comment]
Yeah I understand them will keep threaded safe part which is why I was planning to utilize asynchronous C++ options..

I think I get what you mean by using either or..

I probably just need to read into it a bit more.. so much going on between learning and creating new api features for TWSapi for options trading and learning the dataframe and it’s complexity as well as trying to make it all asynchronous lol.

Ok. Ty again for your reply

Josh Shay
(619)530-7172
Valley Center, CA

**Comment by Sr-316** [comment]
> DataFrame is kind of like a multimap with an analytical interface. You can use either/or DataFrame and/or multimap.
> But you should understand that neither of them is multithreaded safe. Read the multithreading section of DataFrame doc

Do I could possibly ask you some questions and maybe show you what I'm working on and what I got, to see what you think? Since I'm a self taught programmer and self taught trader (taught myself C++, python, sql, JS, solidity, vyper, EOSIO C++ web3, etc... and trading stocks, options, crypto, arbitrage across both types of exchanges as well as stocks... all in the past 2 years... right now I'm automating options trading in c++ using Interactive Brokers Trader Workstation API..

it doesn't provide data for expired options contracts but I've found a way to get algorithmically find options prices for past/expired stock options contracts... 

but I don't truly know the value and level of my skills/knowledge/products since I literally know nobody in either the financial sector nor the programming field..

**Comment by Sr-316** [comment]
Haha awesome. That’s funny I actually beat you to it.. I have that on my screen checking it as we speak. Ty ..
true Programmer Patriot
;)

Josh Shay
(619)530-7172
Valley Center, CA
