### ISSUE TITLE
Hi, everyone. How to get the same result like df.ewm().std()?

### ISSUE THREAD

**Issue by licmue** [hosseinmoein/DataFrame#183]
I use StdVisitor combine with ExponentialRollAdopter, but the result is not same with df.ewm().std().

**Comment by hosseinmoein** [comment]
Yeah, DataFrame implementation is slightly different. Consider using this instead:
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/ExponentiallyWeightedMeanVisitor.html

Also, this is a good discussion
https://stackoverflow.com/questions/37924377/does-pandas-calculate-ewm-wrong

**Comment by licmue** [comment]
Thank you so much! 

Use the implement in this link:
https://stackoverflow.com/questions/37924377/does-pandas-calculate-ewm-wrong
can get the same result!

I can get the same result with df.ewm().mean() by using ExponentiallyWeightedMeanVisitor, you did a great job!
