### ISSUE TITLE
DataFrame across shares libraries (windows DLL)

### ISSUE THREAD

**Issue by TL4903** [hosseinmoein/DataFrame#188]
Hi, thanks for this great library, but I'm having a problem passing a reference/pointer to a DataFrame object across a DLL.  I know templates need explicit specification before passing to a DLL and that's what I believe is causing the HeteroVector to come up empty on the DLL side while other attributes of the object like the size and index get passed correctly.  Do you have any experience on how to get this to work?  I know it's possible to serialize the DataFrame back and forth, but I'd like to avoid that overhead if at all possible.

**Comment by hosseinmoein** [comment]
Unfortunately I am not very familiar with Windows environment (DLL and stuff) development.
Also, I am not sure I completely understand your scenario. Maybe if you show some code snippet, it becomes clearer.

**Comment by TL4903** [comment]
While I agree that this is a stupid/silly mistake when writing the sample program, the problem still persists.  I changed my program to output to file and I still see the issue.

	ULDataFrame                 df;
	df.load_data(std::move(idx_col), std::make_pair("IntCol", int_col));

Exec:
	df.write<std::ostream, int>(std::cout, io_format::csv2);
	df.write<double, int, std::string, hmdf::DateTime>("C:\\temp\\DataFrame\\INPUT.txt", io_format::csv2);

	Work(df);

DLL cpp:

DATAFRAMEWORKDLL_API BOOL __cdecl Work(ULDataFrame& df)
{ 
 df.write<std::ostream, int>(std::cout, io_format::csv2);
 df.write<double, int, std::string, hmdf::DateTime>("C:\\temp\\DataFrame\\OUTPUT.txt", io_format::csv2);

 return TRUE;
}

**Comment by hosseinmoein** [comment]
So writing to cout in DLL works , but writing to file in DLL doesn't work?
what happens? exceptions? empty file?

**Comment by hosseinmoein** [comment]
Then it is kind of behind my expertise. 
Are you running the codebase in master or one of the releases? Since Release 1.20.0, widows compiling became much more organized. That was contributed by @SpaceIm . Maybe he can help?
Also, take a look at file `DataFrameExports.h`. See if that helps to give you a clue.

**Comment by hosseinmoein** [comment]
@TL4903 ,
I am going to close this. But if you find a solution to this, please drop a note here for other people with similar issues
