### ISSUE TITLE
Problem with CMakeFiles.txt

### ISSUE THREAD

**Issue by kotoroshinoto** [hosseinmoein/DataFrame#19]
CMake Error at CMakeLists.txt:107 (set_target_properties):
  set_target_properties Can not find target to add properties to: Dataframe

CMake Error at CMakeLists.txt:113 (target_include_directories):
  Cannot specify include directories for target "Dataframe" which is not
  built by this project.

CMake Error at CMakeLists.txt:117 (install):
  install TARGETS given target "Dataframe" which does not exist in this
  directory.

-- Copying files for testing
-- Copying files for testing - done
-- Configuring incomplete, errors occurred!

**Comment by kotoroshinoto** [comment]
1, you should have an option for making static or shared for either unix/windows
2. please don't use MSVC to detect windows, MINGW also exists, and it will not specify UNIX even though it is a unix/gnu style compiler.

**Comment by hosseinmoein** [comment]
I am not able to reproduce the errors you are getting. Did you follow the instructions?
```
mkdir build
cd build
cmake ..
make install
```
Re/ static vs. dynamic libraries, I agree with you in general. But this is mostly a header-only library. A negligible % of code is actually in the library.

Re/ the enhancements to the Windows make process, I am not very familiar with Windows. 
You are welcome to enhance the make process, in general,  and send me a pull-request.

Best,

**Comment by kotoroshinoto** [comment]
I am on windows using MinGW, not MSVC

**Comment by kotoroshinoto** [comment]
also, I experience compiler errors related to missing template definitions, it seems something done in your CMakeLists.txt ensures the *.tcc files are accounted for somehow, but that doesn't happen automatically upon using #include "DataFrame.h" for instance.

When I fully specify inclusion of all files in your include directory, the compiler stops complaining, but I'm not sure what the difference is between your build environment and mine that lets your tests compile and yet fails for me.

I am intending to include a link to your repo as a git submodule, and as such I want it to build in place and NOT use make install to put it in a system-wide location. Perhaps this is something that breaks the way your code is organized.

Do your headers include the tcc files that they should have within them?

**Comment by kotoroshinoto** [comment]
I found lines such as:

#  ifdef DMS_INCLUDE_SOURCE
#    include "HeteroVector.tcc"
#  endif // DMS_INCLUDE_SOURCE

I've never seen this convention before, what is DMS_INCLUDE_SOURCE ?

**Comment by hosseinmoein** [comment]
To include the tcc files, you have to define `DMS_INCLUDE_SOURCE` on the compile line.
For example `add_definitions(-D DMS_INCLUDE_SOURCE)`, if using cmake

**Comment by kotoroshinoto** [comment]
https://en.wikipedia.org/wiki/Pragma_once

Given this isn't standard, it would be better to use header guards.

I'll see what I can do in a fork and send a pull request.

**Comment by hosseinmoein** [comment]
This is to include template source files for modern C++ compilers.
In older C++ compilers, templates were compiled differently, in a convoluted way using template database.. 
I have structured it this way, so older compiler can potentially work.

**Comment by hosseinmoein** [comment]
This has nothing to do with pragma.

**Comment by kotoroshinoto** [comment]
no, it doesn't, but #pragma once is not a guaranteed portable standard, :

#ifndef GUARD_NAME_HPP
#define GUARD_NAME_HPP
//your code here
#endif //GUARD_NAME_HPP

is a more standard compliant way of doing it.

Its not directly related, but I noticed it when I looked into your headers.

Why do you wrap your include of your tcc files in a preprocessor define anyway? If they absolutely need to be included in order to function, it should ALWAYS be included, and thus no need to use the #  ifdef DMS_INCLUDE_SOURCE wrapper

**Comment by kotoroshinoto** [comment]
Would it not make more sense to assume a newer compiler by default and set instead a flag to refuse automatic inclusion on demand, so if someone is using an ancient compiler that has the problem you have addressed this way they can account for it, and the rest of us don't need to anticipate an obscure preprocessor define that is not a c++ standard way of doing this kind of thing?

**Comment by hosseinmoein** [comment]
True, `#pragma once` is not standard. But it is supported by all major compilers, that I know of.
If you are using a compiler that doesn't support it, let me know.
 
Re/ `DMS_INCLUDE_SOURCE`, as I explained above, it is to have a hook for older style C++ compilers (e.g. Borland) to work.

**Comment by kotoroshinoto** [comment]
I get what you are trying to do here, but if you are assuming #pragma once is supported, does it make sense to also assume the compilers that will have problems with the older style templates?

**Comment by hosseinmoein** [comment]
Yes, perhaps including it by default is not a bad idea. 
My assumptions were that you are using my makefiles, so this is hidden from you.

**Comment by kotoroshinoto** [comment]
I'm trying to make use of cmake's https://cmake.org/cmake/help/latest/module/ExternalProject.html along with git's submodule functionality, to have it build the library in place, and be able to include it from a subdirectory of the project rather than a system-level install.

it would likely have been exposed to any user of your library anyway, unless you set it up to write some kind of pkgconfig or find_package related settings to automatically set that variable somehow, unless the TCC files end up pre-included in the headers during the make install steps. (entirely possible, I haven't tried to install it to see how things get modified.)

**Comment by kotoroshinoto** [comment]
out of curiosity, how old are the compilers that have this inclusion problem?

From what I gathered looking into the preprocessor pragma once, that has been supported for GCC since version 3.4 and msvc since version 4.2, both being ~2013 releases.

What will a compiler do with that pragma in the event that it happens to be old enough to have the problem with templates that you mentioned? (for example the borland compiler), does such a compiler understand what pragma once means?

**Comment by hosseinmoein** [comment]
Yes, some of them do, for example Borland and I think Solaris. But they still use the old style template database mechanism. 
You can remove the DMS_INCLUDE_SOURCE, in your fork. And if it works perfectly for you, I will do some testing on my side to incorporated it.

**Comment by kotoroshinoto** [comment]
it probably wouldn't hurt to use header guards AND pragma once, in case something blunders past it without understanding what it means, so i'll add a few of those in for good measure.

**Comment by hosseinmoein** [comment]
Yeah, currently I have no access to windows machine + compiler. My only way to see if things are working in windows is through appveyer which is very annoying and time consuming.
So, I won't figure out the dll problem for a while
