### ISSUE TITLE
Update dataframe version in package.json & CMakeLists.txt

### ISSUE THREAD

**Issue by SpaceIm** [hosseinmoein/DataFrame#190]
Version is still 1.19.0 in these 2 files, instead of 1.21.0:
https://github.com/hosseinmoein/DataFrame/blob/1.21.0/package.json#L3
https://github.com/hosseinmoein/DataFrame/blob/1.21.0/CMakeLists.txt#L8

In `CMakeLists.txt`, this value controls version & soversion numbers of shared libs on *nix plalforms (https://github.com/hosseinmoein/DataFrame/blob/1.21.0/CMakeLists.txt#L63-L67), as well as the version in pkgconfig & CMake config files.

**Comment by hosseinmoein** [comment]
I don’t have access to a computer at least for a week. If you send me a pull request I can merge it from my phone

**Comment by SpaceIm** [comment]
I can submit a PR, but the idea is to tag the commit where the version has been updated.
