### ISSUE TITLE
add arbitrary delimiter in DateTime

### ISSUE THREAD

**Issue by yegorrr** [hosseinmoein/DataFrame#192]
some databases, like QuestDB use "2021-02-01T21:51:34.443726Z" so i suggest that you parse ISO_STYLE with something like 
`                ::sscanf (str, "%d-%d-%d%c%hd:%hd:%hd.%d", &year, &month, &day, &delimiter, & hour_,
                         &minute_,  &second_, &micros);`
                         
where 'delimiter' is an arbitrary char:

`        char            delimiter;`

**Comment by hosseinmoein** [comment]
This is now done and merged to master
