### ISSUE TITLE
binary '-': 'const _Ty' does not define this operator or a conversion to a type acceptable to the predefined operator

### ISSUE THREAD

**Issue by yegorrr** [hosseinmoein/DataFrame#194]
when bucketizing (even "by_count"), compiler throws this error referring to the line containing 
`src_idx[i] - src_idx[marker]`

under ubuntu with g++ there's no such problem. i guess it's because of time (ctime?) internals? i'm using msvc 2022(v143)

**Comment by hosseinmoein** [comment]
What is the type of your index, when you declare DataFrame?

**Comment by hosseinmoein** [comment]
That is strange because DateTime has an operator that converts it to a double. 
it compiles fine for me on Ubuntu, Mac, and Windows , gcc and VC++

**Comment by yegorrr** [comment]
i also tried 2019 visual studio (v142), it won't compile.
it also doesn't like this bit:
`    struct  DT_initializer  {
        DT_initializer () noexcept  {
#ifdef _WIN32
            _tzset ();
#else
            ::tzset ();
#endif // _WIN32
        }
    };

    inline static const DT_initializer  dt_init_ {  };

    friend class    DT_initializer;`

it shows a warning that type DT_initializer has been declared as a struct and now being declared as a class. so maybe it's confusing that operato(which one btw? something like operator =?) with something else?

**Comment by hosseinmoein** [comment]
You are mixing very old library code with hello world which is new. Those problems were solved sometime ago

**Comment by yegorrr** [comment]
indeed, that source apparently was from the vcpkg package. that's why it didn't build with DataFrame.lib (as i posted in another thread). so i when i got everything from github it worked fined (and on ubuntu i didn't use vcpkg, i was cloning from here). you may check the vcpkg package and edit the instructions, i'm sure it'll confuse a lot of people

**Comment by yegorrr** [comment]
> You are mixing very old library code with hello world which is new. Those problems were solved sometime ago

everywhere in the docs there's
`MyDataFrame df;`

which i assume is an old version? should be something like ULDataFrame  (`StdDataFrame<unsigned long>`)
