### ISSUE TITLE
how to append row to a empty dataframe?

### ISSUE THREAD

**Issue by kkonghao** [hosseinmoein/DataFrame#197]
Hello thanks for your exciting dataframe library. 
I want to create an empty dataframe and append row contents row by row, like a stock's realtime minute open,high,low,close data. when i look for this library document  i found no answer. could you provide an api like append_row() method for that purpose?

**Comment by hosseinmoein** [comment]
You can maintain references -- by using `get_column()` -- to the columns you want to update in real-time and just call _push_back()_.

Because the columns of a DataFrame could have different types an `append_row()` method cannot be implemented cleanly and efficiently.

**Comment by kkonghao** [comment]
> 

yeah,thaks for your quick answer very much ,i think append a row like a map type into an exisit dataframe is necessary for this dataframe although it's efficiency is too slow. but in a dynamic production environment almost all data is row type not column type.
Also pandas provide different methods to append row you can reference.

**Comment by hosseinmoein** [comment]
Yeah, I have to think about this. We don't want to have an convoluted and inefficient interface just for the sake having one

**Comment by hosseinmoein** [comment]
maybe something like `load_data()` would work

**Comment by hosseinmoein** [comment]
This (append_row()) has been implemented and added to master
