### ISSUE TITLE
ERROR: Number of rows requested 1 is more than available rows 2

### ISSUE THREAD

**Issue by SoftwareDogZ** [hosseinmoein/DataFrame#198]
When I called the function get_data_by_rand<...>(random_policy::num_rows_no_seed, 1), it threw an ERROR as mentioned in the title. I don't understand why this function cannot randomly select one row from a two-row dataframe. Then I looked into the corresponding piece of codes (Line 1362 in DataFrame_get.tcc) and I found the code _index_s > 0 && n_rows < index_s - 1_ in the IF-condition. I'm wondering why it's necessary that n_rows is lower than index_s-1 (I think _n_rows <= index_s_ would be correct). Hoping for your response.

**Comment by hosseinmoein** [comment]
I will take a look. Thx

**Comment by hosseinmoein** [comment]
This has been fixed in master
