### ISSUE TITLE
unable to compile in CodeBlocks in windows 10 using mingw64

### ISSUE THREAD

**Issue by Mouli04** [hosseinmoein/DataFrame#202]
iam unable to compile in CodeBlocks in windows 10 using mingw64 error in the image below.

![image](https://user-images.githubusercontent.com/98968731/199251505-1ee9dc1c-0e96-408f-b844-e72514704e3c.png)

![image](https://user-images.githubusercontent.com/98968731/199252206-1de70c09-6858-4267-b8c1-fce268075d16.png)

**Comment by hosseinmoein** [comment]
You need to use C++17 or higher to compile DataFrame

**Comment by Mouli04** [comment]
now tried in visual studio 2022 with C++20 version but getting the below error while compiling with include file

Build started...
1>------ Build started: Project: WindowsProject1, Configuration: Debug x64 ------
1>WindowsProject1.cpp
1>C:\Users\mouli\source\repos\WindowsProject1\WindowsProject1\include\DataFrame\Utils\FixedSizeString.h(87,11): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\mouli\source\repos\WindowsProject1\WindowsProject1\include\DataFrame\Utils\FixedSizeString.h(106,11): error C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\mouli\source\repos\WindowsProject1\WindowsProject1\include\DataFrame\Internals\DataFrame_standalone.tcc(645,11): error C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>Done building project "WindowsProject1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

![image](https://user-images.githubusercontent.com/98968731/199307398-1aab5f02-9fe7-4d1d-995b-1983ad298e93.png)

**Comment by hosseinmoein** [comment]
use this
```
To disable deprecation, use _CRT_SECURE_NO_WARNINGS.
```

**Comment by Mouli04** [comment]
getting below shown error with DataFrame/Utils/Aggregenerator.h else everything seems to be working.

Build started...
1>------ Build started: Project: cppdataframes, Configuration: Debug x64 ------
1>main.cpp
1>C:\Users\mouli\Documents\Projects\Cpp\cppdataframes\include\DataFrame\Utils\Aggregenerator.h(51,1): error C2610: 'hmdf::Aggregenerator<OP,Ts...> hmdf::Aggregenerator<OP,Ts...>::operator =(hmdf::Aggregenerator<OP,Ts...> &&)': is not a special member function or comparison operator which can be defaulted
1>C:\Users\mouli\Documents\Projects\Cpp\cppdataframes\include\DataFrame\Utils\Aggregenerator.h(51,1): message : the return type does not match the expected signature
1>C:\Users\mouli\Documents\Projects\Cpp\cppdataframes\include\DataFrame\Utils\Aggregenerator.h(66): message : see reference to class template instantiation 'hmdf::Aggregenerator<OP,Ts...>' being compiled
1>Done building project "cppdataframes.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by hosseinmoein** [comment]
yeah, Aggregenerator class is not in use anywhere in this repo. I will remove it

**Comment by Mouli04** [comment]
closing the issue...
