### ISSUE TITLE
How to use .pivot or stack function in DataFrame

### ISSUE THREAD

**Issue by WellYixuanDu** [hosseinmoein/DataFrame#206]
I want to use the .pivot and .stack function like pandas, but don't know how to use them, can you tell me which function is used to implement them?

**Comment by hosseinmoein** [comment]
I have not yet implemented multi-level indices and pivot tables.
But since DataFrame columns can be of any type, you can _kind of_ simulate that with having DataFrame of DataFrames

**Comment by WellYixuanDu** [comment]
Thanks for your reply,  if  convenient ,could you give me a easy example to show it,  i can't understand the " with having DataFrame of DataFrames"  DataFrame's column is DataFrame? Sincere thanks.

**Comment by hosseinmoein** [comment]
Yes, That is what I meant, to have a DataFrame that has a DataFrame column.
of course, I do not know exactly what you are trying to do. So, my suggestion may or may not be applicable to your use case
