### ISSUE TITLE
How to retain nan value in csv2 format file when use read() ？

### ISSUE THREAD

**Issue by zhouhaoan** [hosseinmoein/DataFrame#212]
Hello,
I need to process some csv2 data with nan values, nan was saved as ''. According to examples, I try to use `read()` functions, I can successfully read the table and access to colunms by `get_colunm()` method.
However, I found the length of columns are different and those nan values are filtered out when reading the file, the row indexes is also a mixture. I check the help page of `read()` function, it seems there doesn't have option to control whether retain nans or not. So what can I do if I want to retain nan value in original file and keep the row index not change?

Thanks!

**Comment by hosseinmoein** [comment]
Can you post a sample of your data file here? I will take a look

**Comment by hosseinmoein** [comment]
Yeah, currently this will be _undefined_ behavior in DataFrame. It actually shifts the data in the column which will mess up your data alignment.

Can you change `,,` to `,nan,`?

**Comment by hosseinmoein** [comment]
I would like to keep it like that, because it is tidier logic. It is less bug prone

**Comment by zhouhaoan** [comment]
OK，I will try to modify my data, Thanks for answering.
