### ISSUE TITLE
PCG RNG for speed without compromising on spectral characteristics.  

### ISSUE THREAD

**Issue by ttbek** [hosseinmoein/DataFrame#219]
You do use Mersenne Twister, which is good.  It's more than can be said for a lot of other projects.  It is a bit slower than some of the other generators and I saw you wrote in the readme that much of the time in the example is taken up by the RNG.  Have you considered the PCG library?  It is both fast and statistically random.  I've been using it several years now and the igraph library folk have also started using it.  

https://www.pcg-random.org/
https://github.com/imneme/pcg-cpp

I guess this is more of a potential enhancement than a real issue, Mersenne Twister is usually good enough.

**Comment by hosseinmoein** [comment]
Thanks of the comment.
Yeah, I have not paid much attention to RNG so far. But I will take a look
