### ISSUE TITLE
cmake install, preserve directory hierarchy for PUBLIC_HEADER.

### ISSUE THREAD

**Issue by yssource** [hosseinmoein/DataFrame#22]
At present, cmake installs all PUBLIC_HEADER into "${CMAKE_INSTALL_INCLUDEDIR}/${LIBRARY_TARGET_NAME}" without the original directory hierarchy.
For exmaple, 

Actual result:
`/usr/local/include/DataFrame/MMapSharedMem.h`
Expected result:
`/usr/local/include/DataFrame/MMap/MMapSharedMem.h`.

My opinion is that keeping the file structure as it is.
But, do some work in CMakeLists.txt.
It likes, replacing the partials of `PUBLIC_HEADER` with some codes like the following 
``` bash
install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/include/${PROJECT_NAME}" # source directory
        DESTINATION "include" # target directory
        FILES_MATCHING # install only matched files
        PATTERN "*.h|*.tcc" # select header files
)
```

Do you agree with me?

**Comment by hosseinmoein** [comment]
Good point. thanks

**Comment by hosseinmoein** [comment]
Fixed
