### ISSUE TITLE
Can't get_view

### ISSUE THREAD

**Issue by Irantwomiles** [hosseinmoein/DataFrame#220]
I'm having trouble getting a view using a vector of column names, could you please provide a few examples of how I should go about doing that? Here is what I am currently doing:
```
// dataframe 
using index_type = unsigned long;
hmdf::StdDataFrame<index_type> dataframe;

// we add data and columns... etc

std::vector<char *> view_cols{"AREA_ID"};
hmdf::DataFrameView<index_type> view = dataframe.get_view<index_type>(view_cols);
```
Getting an error saying
![image](https://user-images.githubusercontent.com/11483711/208476785-4e140579-9723-469d-80a0-0c856efa446e.png)

**Comment by hosseinmoein** [comment]
One issue might be that the function signature requires: 
```
std::vector<const char *> 
```
you have
```
std::vector<char *>
```
