### ISSUE TITLE
Is there any way of converting epoch to DateTime?

### ISSUE THREAD

**Issue by homedry** [hosseinmoein/DataFrame#221]
There is set_time which is for changing time value. But It seems there is no constructor taking epochType directly.

Is there any way?

**Comment by hosseinmoein** [comment]
You can declare a DateTime with default constructor and then use `set_time()`
```
DateTime  dt;
dt.set_time(<...>)
```

**Comment by homedry** [comment]
Im doing it this way. Thank you for the reply!
