### ISSUE TITLE
Sort failing giving Segmentation Fault

### ISSUE THREAD

**Issue by sierret** [hosseinmoein/DataFrame#224]
I was testing some of the functions and getting used to the library. Everything else seems fine but when attempting to sort I get a segmentation fault error. 

    `using ULDataFrame = StdDataFrame<unsigned long>;
    ULDataFrame df;
    df.create_column<std::string>(static_cast<const char *>("Name"));
    df.create_column<int>(static_cast<const char *>("age"));

    unsigned long   index_val = 0;

    df.append_row(&index_val,
                  std::make_pair("Name", std::string("Poo")),
                  std::make_pair("age", 300));
    df.write<std::ostream, std::string, double, int>(std::cout, io_format::csv2);

    unsigned long val2=index_val+1;
    df.append_row(&val2,
                  std::make_pair("Name", std::string("Poole")),
                  std::make_pair("age", 600));
    df.write<std::ostream, std::string, double, int>(std::cout, io_format::csv2);

    val2+=1;
    df.append_row(&val2,
                  std::make_pair("Name", std::string("Pooley")),
                  std::make_pair("age", 900));
    df.write<std::ostream, std::string, double, int>(std::cout, io_format::csv2);

    string col="age";
    df.sort<std::string, std::string>(col.c_str(),sort_spec::desce);`

**Comment by hosseinmoein** [comment]
This probably should fail more gracefully. But you are specifying the types for `sort` in a wrong way.
For `sort`, first specify the type(s) of column(s) used for sorting then all the types of the DataFrame
So your sort line should be

```
 df.sort<int, std::string, int>(col.c_str(),sort_spec::desce);
```

**Comment by sierret** [comment]
Oh I understand. It works now thanks. 

I may need to open an new issue for this as well, but you might consider adding a absolute value sort, i.e, sort in asc or desc based on the absolute value of a column. It should be trivial to do this with already implemented sort functions by just performing an asc and desc sort on two dataframes and then joining them by row based on column absolute value.

**Comment by hosseinmoein** [comment]
I will put it on my todo list.
But yes please open a new issue
