### ISSUE TITLE
Any efficient way to replace a particular column value( for example by index) without replacing all column values?

### ISSUE THREAD

**Issue by sierret** [hosseinmoein/DataFrame#229]
I was looking for a way to replace an exist column (or row) value? From what I see in the docs, I'd have to reload/replace the entire column with the single adjusted value. Either that or I'd have to delete the entire row and add the new row? Is there an more efficient way to do this that allows only replace on the single row value? Did I miss something?

**Comment by hosseinmoein** [comment]
You don't need to replace the row or column.
The docs are here https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html

Simply call `get_column()` or `get_row()` which returns a reference to a column or a row. Then change whatever you want

**Comment by sierret** [comment]
Oh, it returns a reference! I thought it returned a copy. Thanks!
