### ISSUE TITLE
Does get_column return rows in index order or dataframe order?

### ISSUE THREAD

**Issue by sierret** [hosseinmoein/DataFrame#231]
I'd like to know which orders the references to rows are returned in. Since, after for example a sort operation, the dataframe order may not match the index order.

**Comment by hosseinmoein** [comment]
If you sort the DataFrame, all columns including the index column will be sorted based on your criteria. Unless you opt not to sort the index column which is an option. The default is to sort the index column.

**Comment by sierret** [comment]
Thanks once again!
