### ISSUE TITLE
Adding support for sort column by absolute value. 

### ISSUE THREAD

**Issue by sierret** [hosseinmoein/DataFrame#233]
The sort operation only currently allows for sorting by ascending and descending order. Please consider adding support for an absolute sort whereby the dataframe is sorted on a column by the absolute value of each column row/cell.

In addition, I tried implementing a home-baked solution but that only seemed to erase the whole dataframe. Is there any less efficient solution I could use in the meantime that makes use of the currently available library functions?

**Comment by hosseinmoein** [comment]
I will add that to my todo list.
In the meanwhile you can add a column that has absolute values of your original column and sort with that

**Comment by hosseinmoein** [comment]
This is now implemented and released to master
