### ISSUE TITLE
dataframe_join.tcc miss { }

### ISSUE THREAD

**Issue by hehuaijin** [hosseinmoein/DataFrame#238]
in rows:577
bug code:
   if (*(col_vec_lhs[lhs_current].first) ==
                    *(col_vec_rhs[rhs_current].first))
                joined_index_idx.emplace_back(col_vec_lhs[lhs_current++].second,
                                              col_vec_rhs[rhs_current].second);
            else
                joined_index_idx.emplace_back(
                    std::numeric_limits<size_type>::max(),
                    col_vec_rhs[rhs_current].second);
             rhs_current += 1;

correct code:
   if (*(col_vec_lhs[lhs_current].first) ==
                    *(col_vec_rhs[rhs_current].first))
                joined_index_idx.emplace_back(col_vec_lhs[lhs_current++].second,
                                              col_vec_rhs[rhs_current].second);
            else{
                joined_index_idx.emplace_back(
                    std::numeric_limits<size_type>::max(),
                    col_vec_rhs[rhs_current].second);
             rhs_current += 1;
            }

fix  when right value  match left value only one value.

**Comment by hosseinmoein** [comment]
Thanks you for looking into this.
Why don't you submit this as a PR (pull request)? That way it goes through all the testes and you get the credit for it, if you care about that

**Comment by hehuaijin** [comment]
Tnanks you for replay!&nbsp;
I will try learning&nbsp;submit this as a PR!&nbsp;
&nbsp;


阿黑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hossein ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 晚上9:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hosseinmoein/DataFrame] dataframe_join.tcc miss { } (Issue #238)





 
Thanks you for looking into this.
 Why don't you submit this as a PR (pull request)? That way it goes through all the testes and you get the credit for it, if you care about that

**Comment by hehuaijin** [comment]
Say you're sorry，My apologies for the late reply.Next code a sameple:




/***************************************************************************?
#include <DataFrame/DataFrame.h&gt;&nbsp; // Main DataFrame header
#include <DataFrame/DataFrameFinancialVisitors.h&gt;&nbsp; // Financial algorithms
#include <DataFrame/DataFrameMLVisitors.h&gt;&nbsp; // Machine-learning algorithms
#include <DataFrame/DataFrameStatsVisitors.h&gt;&nbsp; // Statistical algorithms
#include <DataFrame/Utils/DateTime.h&gt;&nbsp; // Cool and handy date-time object
using namespace hmdf;




// A DataFrame with ulong index type
//
using ULDataFrame = StdDataFrame<unsigned long&gt;;


// A DataFrame with string index type
//
using StrDataFrame = StdDataFrame<std::string&gt;;


// A DataFrame with DateTime index type
//
using DTDataFrame = StdDataFrame<DateTime&gt;;


&nbsp;void test_index_left_join() {


	using MyDataFrame = ULDataFrame;
	std::cout << "\nTesting Index Left Join ..." << std::endl;


	std::vector<unsigned long&gt;&nbsp; idx =
	{ 123450, 123451, 123452, 123453, 123454, 123455, 123456, 123457, 123458, 123459, 123460, 123461, 123462, 123466 };
	std::vector<double&gt; djoincol1 = { 1, 1, 1, 1, 1, 1,1, 1, 1, 1, 1, 1, 1, 14 };
	std::vector<double&gt; d1 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
	std::vector<double&gt; d2 = { 8, 9, 10, 11, 12, 13, 14, 20, 22, 23, 30, 31, 32, 1.89 };
	std::vector<double&gt; d3 = { 15, 16, 15, 18, 19, 16, 21, 0.34, 1.56, 0.34, 2.3, 0.34, 19.0 };
	std::vector<int&gt;&nbsp; &nbsp; i1 = { 22, 23, 24, 25, 99 };
	MyDataFrame&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;df;


	df.load_data(std::move(idx),
		std::make_pair("djoincol", djoincol1),
		std::make_pair("col_1", d1),
		std::make_pair("col_2", d2),
		std::make_pair("col_3", d3),
		std::make_pair("col_4", i1));


	std::vector<unsigned long&gt;&nbsp; idx2 =
	{ 123452, 123453, 123455, 123458, 123466, 223450, 223451, 223454, 223456, 223457, 223459, 223460, 223461, 223462 };
	std::vector<double&gt; djoincol2 = { 1 };
	std::vector<double&gt; d12 = { 11 };
	std::vector<double&gt; d22 = { 18 };
	std::vector<double&gt; d32 = { 115 };
	std::vector<int&gt;&nbsp; &nbsp; i12 = { 122 };
	MyDataFrame&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;df2;


	df2.load_data(std::move(idx2),
		std::make_pair("djoincol", djoincol2),
		std::make_pair("xcol_1", d12),
		std::make_pair("col_2", d22),
		std::make_pair("xcol_3", d32),
		std::make_pair("col_4", i12));


	std::cout << "First DF:" << std::endl;
	df.write<std::ostream, double, int&gt;(std::cout);
	std::cout << "Second DF2:" << std::endl;
	df2.write<std::ostream, double, int&gt;(std::cout);


	auto join_df =
		df.join_by_column<decltype(df2), double, int&gt;(df2,"djoincol", hmdf::join_policy::left_join);


	std::cout << "Now The joined DF:" << std::endl;
	join_df.write<std::ostream, double, int&gt;(std::cout);
}
&nbsp;


阿黑
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hossein ***@***.***&gt;; 
发送时间: 2023年5月3日(星期三) 上午7:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hosseinmoein/DataFrame] dataframe_join.tcc miss { } (Issue #238)





 
Closed #238 as completed.
 
&mdash;

**Comment by hehuaijin** [comment]
Say you're sorry，My apologies for the late reply.

This is a sample:

/*******************************************/
#include <DataFrame/DataFrame.h>  // Main DataFrame header
#include <DataFrame/DataFrameFinancialVisitors.h>  // Financial algorithms
#include <DataFrame/DataFrameMLVisitors.h>  // Machine-learning algorithms
#include <DataFrame/DataFrameStatsVisitors.h>  // Statistical algorithms
#include <DataFrame/Utils/DateTime.h>  // Cool and handy date-time object
using namespace hmdf;


// A DataFrame with ulong index type
//
using ULDataFrame = StdDataFrame<unsigned long>;

// A DataFrame with string index type
//
using StrDataFrame = StdDataFrame<std::string>;

// A DataFrame with DateTime index type
//
using DTDataFrame = StdDataFrame<DateTime>;

 void test_index_left_join() {

	using MyDataFrame = ULDataFrame;
	std::cout << "\nTesting Index Left Join ..." << std::endl;

	std::vector<unsigned long>  idx =
	{ 123450, 123451, 123452, 123453, 123454, 123455, 123456, 123457, 123458, 123459, 123460, 123461, 123462, 123466 };
	std::vector<double> djoincol1 = { 1, 1, 1, 1, 1, 1,1, 1, 1, 1, 1, 1, 1, 14 };
	std::vector<double> d1 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
	std::vector<double> d2 = { 8, 9, 10, 11, 12, 13, 14, 20, 22, 23, 30, 31, 32, 1.89 };
	std::vector<double> d3 = { 15, 16, 15, 18, 19, 16, 21, 0.34, 1.56, 0.34, 2.3, 0.34, 19.0 };
	std::vector<int>    i1 = { 22, 23, 24, 25, 99 };
	MyDataFrame         df;

	df.load_data(std::move(idx),
		std::make_pair("djoincol", djoincol1),
		std::make_pair("col_1", d1),
		std::make_pair("col_2", d2),
		std::make_pair("col_3", d3),
		std::make_pair("col_4", i1));

	std::vector<unsigned long>  idx2 =
	{1 };
	std::vector<double> djoincol2 = { 1 };
	std::vector<double> d12 = { 11 };
	std::vector<double> d22 = { 18 };
	std::vector<double> d32 = { 115 };
	std::vector<int>    i12 = { 122 };
	MyDataFrame         df2;

	df2.load_data(std::move(idx2),
		std::make_pair("djoincol", djoincol2),
		std::make_pair("xcol_1", d12),
		std::make_pair("col_2", d22),
		std::make_pair("xcol_3", d32),
		std::make_pair("col_4", i12));

	std::cout << "First DF:" << std::endl;
	df.write<std::ostream, double, int>(std::cout);
	std::cout << "Second DF2:" << std::endl;
	df2.write<std::ostream, double, int>(std::cout);

	auto join_df =
		df.join_by_column<decltype(df2), double, int>(df2,"djoincol", hmdf::join_policy::left_join);

	std::cout << "Now The joined DF:" << std::endl;
	join_df.write<std::ostream, double, int>(std::cout);
}



write out:

Testing Index Left Join ...
First DF:
INDEX:14:<ulong>:123450,123451,123452,123453,123454,123455,123456,123457,123458,123459,123460,123461,123462,123466,
djoincol:14:<double>:1,1,1,1,1,1,1,1,1,1,1,1,1,14,
col_1:14:<double>:1,2,3,4,5,6,7,8,9,10,11,12,13,14,
col_2:14:<double>:8,9,10,11,12,13,14,20,22,23,30,31,32,1.89,
col_3:14:<double>:15,16,15,18,19,16,21,0.34,1.56,0.34,2.3,0.34,19,nan,
col_4:14:<int>:22,23,24,25,99,0,0,0,0,0,0,0,0,0,

Second DF2:
INDEX:1:<ulong>:1,
djoincol:1:<double>:1,
xcol_1:1:<double>:11,
col_2:1:<double>:18,
xcol_3:1:<double>:115,
col_4:1:<int>:122,

Now The joined DF:
INDEX:14:<uint>:0,1,2,3,4,5,6,7,8,9,10,11,12,13,
djoincol:14:<double>:1,1,1,1,1,1,1,1,1,1,1,1,1,14,
lhs.col_4:14:<int>:22,23,24,25,99,0,0,0,0,0,0,0,0,0,
rhs.col_4:14:<int>:122,0,0,0,0,0,0,0,0,0,0,0,0,0,


Should be:
djoincol:14:<double>:1,1,1,1,1,1,1,1,1,1,1,1,1,14,
lhs.col_4:14:<int>:22,23,24,25,99,0,0,0,0,0,0,0,0,0,
rhs.col_4:14:<int>:122,122,122,122,122,122,122,122,122,122,122,122,122,nan,

**Comment by hosseinmoein** [comment]
I am a bit confused. The code that your are saying is wrong and you corrected (line# 577 in file DataFrame_join.tcc) is for the `left right` join (aka merge). The code example above is for `left` outer join. In other words, the example above doesn't execute the code you corrected.

**Comment by hehuaijin** [comment]
The similar bug more than one. I post the fix code, and comments by : "//add this row to fix".

**Comment by hehuaijin** [comment]
I submit pr for the first time，may be some wrong.

**Comment by hosseinmoein** [comment]
Thank you for looking into this. But I believe the original behavior/code is correct. making your changes will introduce the bug of repeating the _RHS_ values where they shouldn't be there

Also your code sample above is missing some type specifications. The correct code is:
```
static void test_index_left_join()  {

    using MyDataFrame = ULDataFrame;
    std::cout << "\nTesting Index Left Join ..." << std::endl;

    std::vector<unsigned long>   idx =
        { 123450, 123451, 123452, 123453, 123454, 123455, 123456, 123457,
          123458, 123459, 123460, 123461, 123462, 123466 };
    std::vector<double>          djoincol1 =
        { 1, 1, 1, 1, 1, 1,1, 1, 1, 1, 1, 1, 1, 14 };
    std::vector<double>          d1 =
        { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
    std::vector<double>          d2 =
        { 8, 9, 10, 11, 12, 13, 14, 20, 22, 23, 30, 31, 32, 1.89 };
    std::vector<double>          d3 =
        { 15, 16, 15, 18, 19, 16, 21, 0.34, 1.56, 0.34, 2.3, 0.34, 19.0 };
    std::vector<int>             i1 = { 22, 23, 24, 25, 99 };
    MyDataFrame                 df;

    df.load_data(std::move(idx),
                 std::make_pair("djoincol", djoincol1),
                 std::make_pair("col_1", d1),
                 std::make_pair("col_2", d2),
                 std::make_pair("col_3", d3),
                 std::make_pair("col_4", i1));

    std::vector<unsigned long>   idx2 = {1 };
    std::vector<double>          djoincol2 = { 1 };
    std::vector<double>          d12 = { 11 };
    std::vector<double>          d22 = { 18 };
    std::vector<double>          d32 = { 115 };
    std::vector<int>             i12 = { 122 };
    MyDataFrame                 df2;

    df2.load_data(std::move(idx2),
                  std::make_pair("djoincol", djoincol2),
                  std::make_pair("xcol_1", d12),
                  std::make_pair("col_2", d22),
                  std::make_pair("xcol_3", d32),
                  std::make_pair("col_4", i12));

    std::cout << "First DF:" << std::endl;
    df.write<std::ostream, double, int>(std::cout, io_format::csv2);
    std::cout << "Second DF2:" << std::endl;
    df2.write<std::ostream, double, int>(std::cout, io_format::csv2);

    auto join_df =
        df.join_by_column<decltype(df2), double, double, int>
            (df2, "djoincol", hmdf::join_policy::left_join);

    std::cout << "Now The joined DF:" << std::endl;
    join_df.write<std::ostream, double, int, unsigned long>
        (std::cout, io_format::csv2);
}
```

**Comment by hehuaijin** [comment]
/***********left table:*******************************/
    std::vector<double> 
         djoincol1 = { 1, 1, 1, 1, 1, 1,1, 1, 1, 1, 1, 1, 1, 14 };
    std::vector<double>          d1 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };

/***********right table:*******************************/
djoincol1 = { 1}
  std::vector<double>          d2 = {2}
/***********right table:*******************************/
join on  left.djoincol1 =right.djoincol1 
I think  result  should be:
 d1 = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
 d2 = { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, nan };

**Comment by hosseinmoein** [comment]
I believe the left join result should be
```
d2 = { 2, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan };
```
The rhs has only one `2` value and if you repeat them it means you are manufacturing data
