### ISSUE TITLE
Support Series?

### ISSUE THREAD

**Issue by yssource** [hosseinmoein/DataFrame#24]
Is there any plan to support **Series** as what Pandas does?

**Comment by yssource** [comment]
It would be convenient to do numerical analysis base on columns if it is with Series supported.

Col_C = Col_A + Col_B.

**Comment by yssource** [comment]
Now, it can slice DataFrame by index `get_data_by_idx`.
And I would like have more features supported. like `get_data_by_column`

For example, like Pandas do.
### Slicing DataFrame by columns' value.
``` python
df[df['A'] > 0]
```
``` python
df.loc[lambda df: df.A > 0, :]
```

**Comment by yssource** [comment]
A workaround for me to slice DataFrame by columns' value.
`get_column` to filter my column value with some criteria, and then
`get_data_by_loc`

**Comment by hosseinmoein** [comment]
I don't have a plan to add Series in the near future unless there is a good reason for it. Each column is a series anyway. Can you explain why a Series is necessary? Even in Pandas, I don't get why Series is necessary.

A lot of functionalities you mention above here are doable by `Functors`. Please see `DataFrameVisitors.h` and `DataFrameOperators.h` files and the test file `dataframe_tester.cc`.

The column filter you mention is something I was thinking to add as a visitor. I am thinking about the best way to implement that and will add it in near future. If you have any idea how to implement it or you want to implement it and send me a pull request, please let me know.

**Comment by hosseinmoein** [comment]
basically I am thinking about something like this
```
template<typename ... types, typename F>
get_data_by_select(const std::array<const char *, N> col_names, F functor);

template<typename ... types, typename F>
get_view_by_select(const std::array<const char *, N> col_names, F functor);
```
What do you think?

**Comment by yssource** [comment]
> A lot of functionalities you mention above here are doable by Functors. Please see DataFrameVisitors.h and DataFrameOperators.h files and the test file dataframe_tester.cc.

So far, these operations have been row-based. I wonder if column-based operations can be used?
And most of visitors are Reducers Functor based on row-major.

I think it is not necessary to have Series.  But it would be helpful to have some operations for cross-column in one internal DataFrame.

> basically I am thinking about something like this

`get_data_by_select` it is supposed to be different with `get_data_by_idx|loc`, which accept a Range as a input argument. While, I think the functor for `get_data_by_select` would work on both a Range and a vector containing discrete values.

**Comment by hosseinmoein** [comment]
I will do this in the next few days

**Comment by hosseinmoein** [comment]
@yssource 
Added `get_data_by_del()` for up to 3 columns for now. Please see the documentation in doc file and example in `dataframe_tester.cc` file.

Please let me know, if there is an issue.

**Comment by yssource** [comment]
Thank you. No problem has been found yet.
`get_data_by_sel` It works as I expected.

**Comment by hosseinmoein** [comment]
I just also released the implementation of views for boolean data selection.
See `get_view_by_sel()` vs. `get_data_by_sel()`
