### ISSUE TITLE
Dataframe length

### ISSUE THREAD

**Issue by federicomartinlara1976** [hosseinmoein/DataFrame#243]
Is there a method to get the dataframe length?

Thanks.

**Comment by hosseinmoein** [comment]
I am not sure what you mean by _length of the DataFrame_. Each column in the DataFrame can be of different length but not longer than the index columns
The documentation is here https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html. It is worth reading it. It is short and to the point

Also look at DataFrame member functions `describe()` and `shape()`

**Comment by federicomartinlara1976** [comment]
Thanks.

I figured it out when using the indices column. The size is obtained from
the associated vector.
-----------------------------------------------------------------------------------------------------------------------------------------

*Federico Martín Lara*


*Jefe de Proyectos*
Tfno. 680496138
email: ***@***.***

ESOLUZION CONSULTING, S.L.
Paseo de la Castellana 179, piso 1 Oficina C1 28046 Madrid
Tel.: 91 286 56 52 - Fax: 91 188 14 75

Consulting eSoluzion S.A.SFilial Bogotá.
Cl. 19 N.7-48. Of 1703 Ed covinoc Bogotá.

http://www.esoluzion.com
