### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by ludeen007** [hosseinmoein/DataFrame#269]
Thanks for this excellent project!
I run a test that failed.
I install DataFrame with vcpkg, try it on VS2022 17.8.1, with x64 Debug build settings.
Then I encountered a assert failed. file test/dataframe_tester_2.cc, line 400:
assert(result[10] == static_cast<unsigned long>(-1));
after debug, I change that line as below to fix:
assert(result[10] == static_cast<unsigned long>(-1));

**Comment by hosseinmoein** [comment]
I think you had a problem in your copy/past. I don't see a difference in what it was and what you say it should be
