### ISSUE TITLE
Unit tests fail on Windows when compiled with MinGW-W64

### ISSUE THREAD

**Issue by thekvs** [hosseinmoein/DataFrame#27]
```
$ ctest.exe
Test project C:/Users/expadmin/Work/DataFrame/build
    Start 1: dataframe_tester
1/5 Test #1: dataframe_tester .................***Failed    0.05 sec
    Start 2: vectors_tester
2/5 Test #2: vectors_tester ...................   Passed    0.01 sec
    Start 3: date_time_tester
3/5 Test #3: date_time_tester .................***Failed    0.02 sec
    Start 4: obj_vector_tester
4/5 Test #4: obj_vector_tester ................   Passed    0.01 sec
    Start 5: obj_vector_erase_tester
5/5 Test #5: obj_vector_erase_tester ..........   Passed    0.01 sec

60% tests passed, 2 tests failed out of 5

Total Test time (real) =   0.10 sec

The following tests FAILED:
          1 - dataframe_tester (Failed)
          3 - date_time_tester (Failed)
Errors while running CTest
```
```
$ g++.exe --version
g++.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Also please consider adding MinGW suite on AppVeyor.

**Comment by hosseinmoein** [comment]
I have no access to this compiler and windows development environment.
Can you tell me why and where the tests are failing?
Perhaps I can help you fix it and send another pull request.

**Comment by thekvs** [comment]
Maybe you can use https://developer.microsoft.com/en-us/windows/downloads/virtual-machines ?

**Comment by hosseinmoein** [comment]
Yeah, with my current work load it would be a while before I can go through that.

**Comment by thekvs** [comment]
Here is some output from failed test run manually:
```
...

Testing get_row()
Original DF:
INDEX:14:<ulong>:123450,123451,123452,123453,123454,123455,123456,123457,123458,123459,123460,123461,123462,123466,
col_4:14:<int>:22,11,34,25,0,0,0,0,0,0,0,0,0,0,
col_int:2:<int>:22,11,
col_3:14:<double>:400.4,16,500.5,18,19,16,nan,0.34,1.56,0.34,2.3,0.34,nan,nan,
col_1:14:<double>:1,2,3,4,nan,6,7,nan,nan,nan,11,12,13,14,
col_str:8:<string>:qqqq,wwww,eeee,rrrr,tttt,yyyy,iiii,oooo,
col_2:14:<double>:8,9,10,11,12,nan,nan,20,22,23,30,31,nan,1.89,


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
```

**Comment by thekvs** [comment]
full output:
[DayaFrame.test.out.txt](https://github.com/hosseinmoein/DataFrame/files/3306551/DayaFrame.test.out.txt)

**Comment by hosseinmoein** [comment]
This indicates to me the the executable was not compiled properly with the correct std libraries.
Is the compiler C++17 capable? Does the machine you run it on has enough memory?
This test uses relatively small memory space. And I cannot reproduce this under any other environment.
When I get a chance over the weekend , I will hopefully look further into it.

**Comment by thekvs** [comment]
It should be C++17 capable. Actually MinGW is GCC at its core and compiler's version is 8.1 which should support C++17 pretty well.

**Comment by hosseinmoein** [comment]
This may (or may not) explain your problem

```
https://stackoverflow.com/questions/18157464/c-helloworld-program-compiled-with-mingw-crashes-with-illegal-argument
```

**Comment by thekvs** [comment]
I've copied all MinGW's DLLs into the same folder where executable is located so AFAIK Windows's linker should load them first but unit tests still fail:
```
$ objdump.exe -p dataframe_tester.exe | grep "DLL Name:"
        DLL Name: libgcc_s_dw2-1.dll
        DLL Name: KERNEL32.dll
        DLL Name: msvcrt.dll
        DLL Name: libwinpthread-1.dll
        DLL Name: USER32.dll
        DLL Name: libstdc++-6.dll

$ ls -l *.dll
-rwxr-xr-x 1 expadmin 197121  116238 Jun 20 01:10 libgcc_s_dw2-1.dll*
-rwxr-xr-x 1 expadmin 197121  168974 Jun 20 01:10 libgomp-1.dll*
-rwxr-xr-x 1 expadmin 197121 1557006 Jun 20 01:10 libstdc++-6.dll*
-rwxr-xr-x 1 expadmin 197121   47104 Jun 20 01:10 libwinpthread-1.dll*
```

**Comment by thekvs** [comment]
BTW, this is how another tests fails:
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\Users\expadmin\Work\DataFrame\build\bin\date_time_tester.exe
File: C:\Users\expadmin\Work\DataFrame\test\date_time_tester.cc, Line 756

Expression: dt1.long_time() == 1558538105123456789
```

**Comment by hosseinmoein** [comment]
This error (date_time_tester) is kind of understandable. You may not have up-to-date New York timezone info on your machine. You could print the `dt1.long_time()` to `cout`. The diff should be one hour.


But the first error looks vey much like what is being discussed in the stackoverflow.
For the first error, I am almost certain you are not linking with the correct libstdc++.

**Comment by thekvs** [comment]
> You may not have up-to-date New York timezone info on your machine.

Yes, it is rather old Windows. I am not sure that it has all necessary updates installed.

**Comment by thekvs** [comment]
As for the `libstdc++` -- I am developing an app in C++17 on this machine and it runs without any issues, though it is not multi-threaded.

**Comment by hosseinmoein** [comment]
Wrong `libstdc++` doesn't mean you would crash under all circumstances. In your program, use `std::vector::reserve()` and see if it works.

I really cannot think of any other issue that would cause a crash like yours. And the fact remains that it only happens under your particular environment. This library works for several people under Windows/MVC++, various Linux flavors, different versions of MacOS.

**Comment by thekvs** [comment]
Yes, I use `std::vector::reserve()`, just double checked it. Maybe this crash is MinGW specific? For some reasons we'd like to use MinGW.

**Comment by hosseinmoein** [comment]
ohh yes. This is MinGW specific. I thought your other program was also in MinGW environment.
The problem as discussed in `stackoverflow` is that your MinGW compiled code is picking the default (i.e. mvc++ version) of libstdC++.  The MinGW should come with its own libstdC++, ... version of libraries. and at link time you have to link with them.

**Comment by thekvs** [comment]
I think it is picking the right version. See https://github.com/hosseinmoein/DataFrame/issues/27#issuecomment-503651654

**Comment by thekvs** [comment]
> I thought your other program was also in MinGW environment.
Yes it is in MinGW env. As I've said we use MinGW for our development.

**Comment by thekvs** [comment]
Just want to point out that we use 32-bit version of MinGW. Windows itself where all this happens is 64-bit, but in production code will run on 32-bit Windows system.

**Comment by hosseinmoein** [comment]
That might also be very well an inconsistency. I do not know anybody that uses this library in 32bit environment. There are differences between 32bit and 64bit types in C++. For example `long int` type has different precision in 32 vs. 64 bit versions.
So I do recommend compiling in 64bit environment only.

**Comment by thekvs** [comment]
Just a wild guess: maybe there is integer overflow happened and `std::vector::reserve()` received a huge number as its parameter?

**Comment by hosseinmoein** [comment]
It is very possible.
Also in several places I use `long long int` which although supported by 32bit compilers are known to be troublesome/error prone.
