### ISSUE TITLE
failed to compile tests and examples in ubuntu

### ISSUE THREAD

**Issue by jincaijiang** [hosseinmoein/DataFrame#276]
Found below errors when trying to compile examples in Linux system.

cmake -DCMAKE_BUILD_TYPE=Debug -DHMDF_EXAMPLES=ON ..
make

> [ 16%] Building CXX object test/CMakeFiles/dataframe_tester.dir/dataframe_tester.cc.o
> In file included from DataFrame/include/DataFrame/DataFrame.h:4081,
>                  from DataFrame/test/dataframe_tester.cc:28:
> DataFrame/include/DataFrame/Internals/DataFrame.tcc: In member function ‘void hmdf::DataFrame<I, H>::sort(const char*, hmdf::sort_spec, bool)’:
> DataFrame/include/DataFrame/Internals/DataFrame.tcc:748:39: error: ‘zip’ is not a member of ‘std::ranges::views’
>   748 |     auto    zip = std::ranges::views::zip(*vec, sorting_idxs);
>       |                                       ^~~
> DataFrame/include/DataFrame/Internals/DataFrame.tcc:749:43: error: ‘zip’ is not a member of ‘std::ranges::views’
>   749 |     auto    zip_idx = std::ranges::views::zip(*vec, indices_, sorting_idxs);
>  ...

OS: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
g++ version: g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by hosseinmoein** [comment]
This means your compiler is not fully C++23 compliant. 
I may have to put some #def around `zip`. But it is going to take me a while

**Comment by hosseinmoein** [comment]
https://gcc.gnu.org/gcc-13/changes.html
