### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by sursu** [hosseinmoein/DataFrame#3]
The library lacks documentation.

How do you read a `.csv` file?

**Comment by hosseinmoein** [comment]
You are right I have to add it.
Although file `DataFrame.h` has a lot of comments inside of it.
In Linux csv files are read using mmap interface through `read_csv()write_csv()`.
@justinjk007 is adding support for Windows which will read csv files using regular file interface.
There is a sample csv file in the repository that the test program reads.


BTW, I welcome all contributions

**Comment by hosseinmoein** [comment]
Added more documentation
