### ISSUE TITLE
std::max causing syntax error if not put in parentheses

### ISSUE THREAD

**Issue by northstarvn** [hosseinmoein/DataFrame#328]
I wonder if it's a problem of MSVC and how to avoid mass code changes to compile successfully?
everywhere a max, min like that has the same issue. E.g
must wrap parentheses like this (std::numeric_limits<std::size_t>::max)()

**Comment by hosseinmoein** [comment]
Yes, this is because of the stupid Windows historical definition of min/max.
My original solution was 
```
#ifdef _WIN32 && max
  undef max
#endif
```

But another contributor solved it better. If you include the DataFrame.h, it should just work with CMake
