### ISSUE TITLE
use dataframe question

### ISSUE THREAD

**Issue by winer-lch** [hosseinmoein/DataFrame#331]
r  diff(range(x)) ,in the dataframe, How to imitate, or use similar

**Comment by hosseinmoein** [comment]
No, there is no connection between R packages and C++ DataFrame

**Comment by winer-lch** [comment]
thank you，I have one more question，in  join_by_column，How to do multiple keyword data merge

**Comment by hosseinmoein** [comment]
I am not sure what you mean. If you mean joining by multiple columns, I don't have that currently. You can always build an extra column that contains your multiple keys and join on that.
Also, look at `bucketize` and `groupby`

**Comment by winer-lch** [comment]
remove_duplicates ，Is it equivalent to unique.matrix in r? Why does it take so much time？

**Comment by winer-lch** [comment]
in the dataframe，Which method is equivalent to merge in r

**Comment by hosseinmoein** [comment]
I am not an R expert but I guess `remove_duplicates` and `unique.matrix` are similar. 

Re/ slowness, compared with what? Do you have any timing numbers? I haven't look at `remove_duplicates` implementation for a long time. I will take another another look

**Comment by hosseinmoein** [comment]
Ok, a couple of points:
1. I changed the code in master for `remove_duplicates()` to be a little faster. It was a rather naive algorithm.
2. If you are doing this with a large dataset (n > 250k), turn on the multithreading in DataFrame.

Please let me know, if you see any improvements in your case.

**Comment by winer-lch** [comment]
I have about 100,000 data, I suggest the author test this function remove_duplicates, normally, I think it should be millisecond level, now I rewrote this function on the basis of this framework, the performance is barely enough, thank the author, the problem has been solved

**Comment by hosseinmoein** [comment]
I don't think so. What does it do?

**Comment by winer-lch** [comment]
I need to complete the distance-based hierarchical clustering

**Comment by hosseinmoein** [comment]
Look at `Clustering Algorithms` in documentation.

**Comment by hosseinmoein** [comment]
BTW, another version of `remove_duplicates()` was released to master that is even faster.

**Comment by winer-lch** [comment]
Thank you. You've been very helpful
