### ISSUE TITLE
The README benchmark is strongly out-of-date

### ISSUE THREAD

**Issue by adrian17** [hosseinmoein/DataFrame#332]
From what I see, the last time the benchmark files or results were updated was 10 months ago. Surely all three compared libraries could have significantly changed since then.

Also, polars now shows a deprecation warning:

```
polars_performance.py:33: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
  print(f"Number of rows after select: {df3.select(pl.count()).item()}")
```

**Comment by hosseinmoein** [comment]
Running the benchmarks and its supporting processes takes me a few hours. I will find some time in the future to rerun them.
In the meantime, in the README, I note exactly the versions of all packages used. So there should be no confusion as to what I am comparing against what.
