### ISSUE TITLE
DateTime format conversion

### ISSUE THREAD

**Issue by anthai0908** [hosseinmoein/DataFrame#342]
Hi, Hossein.

I want to ask you about datetime format conversion of index column. When I read the csv file, the index column is in DT_TM2 format. I want to know how to convert it into DT_ISO before writing it. Thank you

**Comment by hosseinmoein** [comment]
If I understand the question correctly, once you read a DateTime (or have an instance of DataTime in general) you can write it in any format using `string_format()` and specifying desired format (i.e ISO_DT).

If you mean how to change the format in place in the file, I have nothing for that. You can accomplish that with a simple C++ or Python script.

**Comment by anthai0908** [comment]
Thank you for your reply, I mean I have `auto &index = dt.df.get_index()`,  and all index values are in `DD/MM/YYYY hh:mm:ss:mmm`. How can I turn my index values into `ISO_DT (YYYY-MM-DD)`. I have tried to used `index[i].string_format(DT_FORMAT::ISO_DT);` with loop but it didn't work.

**Comment by anthai0908** [comment]
Update: I have converted. But still want to know to do it without looping each datetime instance. And do I need to convert new values back to DateTime format?

**Comment by hosseinmoein** [comment]
I am not sure I understand what you mean? These formats are only applicable when you print out or convert a DateTime to a string. DateTime itself keeps that data in its own binary format.
Maybe if you show me a code snippet it would help to see what you are trying to do

**Comment by anthai0908** [comment]
This is my csv file format
INDEX::<DateTimeISO>,Open::<double>,High::<double>,Low::<double>,Close::<double>,Volume::<long>
1980-12-12,0.0991,0.0995,0.0991,0.0991,469033600
1980-12-15,0.0944,0.0944,0.0939,0.0939,175884800
1980-12-16,0.0874,0.0874,0.0870,0.0870,105728000
1980-12-17,0.0892,0.0896,0.0892,0.0892,86441600
1980-12-18,0.0918,0.0922,0.0918,0.0918,73449600
1980-12-19,0.0974,0.0978,0.0974,0.0974,48630400
1980-12-22,0.1021,0.1025,0.1021,0.1021,37363200
1980-12-23,0.1064,0.1068,0.1064,0.1064,46950400
1980-12-24,0.1120,0.1125,0.1120,0.1120,48003200
1980-12-26,0.1223,0.1228,0.1223,0.1223,55574400
1980-12-29,0.1241,0.1245,0.1241,0.1241,93161600
1980-12-30,0.1215,0.1215,0.1210,0.1210,68880000
1980-12-31,0.1180,0.1180,0.1176,0.1176,35750400. 

When I read this csv file to get index column
 `DTDataFrame dt_df;
 dt_df.read(file_name, io_format::csv2);
 auto &index = dt_df.get_index();`. 
 When I print dt_df
`std::cout << "Index       Open    High    Low    Close" << std::endl;
        for (size_t i = 0; i < std::min(index.size(), index.size()); ++i) {
            std::cout <<std::setw(25) << std::left << index[i] 
                      <<std::setw(10) << std::left << column1[i] 
                      <<std::setw(10) << std::left << column2[i] 
                      <<std::setw(10) << std::left << column3[i] 
                      <<std::setw(10) << std::left << column4[i] << std::endl;`, 
it has shown this 
11/13/2020 00:00:00.000  116.799   117.025   115.263   116.623   
11/16/2020 00:00:00.000  116.29    118.314   115.533   117.64    
11/17/2020 00:00:00.000  116.906   118.005   116.329   116.75    
11/18/2020 00:00:00.000  115.987   117.17    115.391   115.42    
11/19/2020 00:00:00.000  114.99    116.427   114.227   116.016   
11/20/2020 00:00:00.000  116.016   116.144   114.696   114.745   
11/23/2020 00:00:00.000  114.589   115.019   111.234   111.332   
11/24/2020 00:00:00.000  111.391   113.288   110.1     112.623   
11/25/2020 00:00:00.000  112.995   114.168   112.623   113.464   
11/27/2020 00:00:00.000  113.992   114.892   113.65    114.012   
11/30/2020 00:00:00.000  114.383   118.295   114.227   116.417   
12/01/2020 00:00:00.000  118.334   120.739   117.356   120.006   
12/02/2020 00:00:00.000  119.322   120.642   118.217   120.358   
12/03/2020 00:00:00.000  120.788   121.043   119.507   120.221   
12/04/2020 00:00:00.000  119.889   120.144   118.833   119.546. 
I mean how to change index values into original format when I read csv file? And do we have any function/method similar to pandas(df['index'].stringtify() or df['index'] = pd.to_datetime()? Thank you

**Comment by hosseinmoein** [comment]
First, please print the first line of your data file properly, so I can see the index type spec in the file

Second, what does this mean?
```
std::min(index.size(), index.size())
```

Third, you are printing the index (DataTime) in its default string format which happens to be `DT_FORMAT::DT_TM2`
You want the print like this
```
index[i].string_format(DT_FORMAT::ISO_DT);
```

**Comment by anthai0908** [comment]
I have defined format of the columns in my csv file as below:
`INDEX::<DateTimeISO>,Open::<double>,High::<double>,Low::<double>,Close::<double>,Volume::<long>`.
I think the index column in my csv file is in DatetimeISO format.

For this line:  
`std::min(index.size(), index.size())`, please ignore it, just a mistyping.

**Comment by hosseinmoein** [comment]
DateTime is not in any particular format. But it can render itself in all those formats. So for example if your index is in DateTime ISO format, you can still print it (render it) in any other format. Does that make sense?

**Comment by anthai0908** [comment]
Oh I got it. Yeah you are right. So is there anyway to write it with specific format? I have written a new csv file, and it in below format with 'MM/DD/YYYY' not the one I want
INDEX:11073:<DateTime>,Open:11073:<double>,High:11073:<double>,Low:11073:<double>,Close:11073:<double>,Volume:11073:<long>,RSI-14:11073:<double>
12/12/1980 00:00:00.000,0.0991,0.0995,0.0991,0.0991,469033600,nan
12/15/1980 00:00:00.000,0.0944,0.0944,0.0939,0.0939,175884800,nan
12/16/1980 00:00:00.000,0.0874,0.0874,0.087,0.087,105728000,nan
12/17/1980 00:00:00.000,0.0892,0.0896,0.0892,0.0892,86441600,nan
12/18/1980 00:00:00.000,0.0918,0.0922,0.0918,0.0918,73449600,nan
12/19/1980 00:00:00.000,0.0974,0.0978,0.0974,0.0974,48630400,nan
12/22/1980 00:00:00.000,0.1021,0.1025,0.1021,0.1021,37363200,nan
12/23/1980 00:00:00.000,0.1064,0.1068,0.1064,0.1064,46950400,nan
12/24/1980 00:00:00.000,0.112,0.1125,0.112,0.112,48003200,nan

**Comment by hosseinmoein** [comment]
Yes. I already answered it above. Also, see the documentation specifically for `string_format()`

**Comment by hosseinmoein** [comment]
The column or index type of DateTime is always rendered as its default format which is `DT_FORMAT::DT_TM2`. But once you load that data into a DataFrame, then you can rendered them in any format through your program.

Currently, I don't have a way to write it into file in any other format.
Just out of curiosity, why the format matters when saving into a file. The saved file should be opaque.

**Comment by hosseinmoein** [comment]
Also, read the documentation for `read()`.
If you have an already saved file in ISO format that you want to load into a DataFrame, you can do that by specifying the index type as `DateTimeISO`.
