### ISSUE TITLE
Any plan to make data interchangeable with Pandas dataframe

### ISSUE THREAD

**Issue by fanbin** [hosseinmoein/DataFrame#35]
Probably could supply an interface to transform data from Pandas dataframe to C++'s dataframe

**Comment by hosseinmoein** [comment]
It is a good idea, although I do not have the time to do it currently. This is not very trivial. You have to know the internals of Pandas and how it uses Numpy very well to do it. Isn't that the case?
I welcome contributions. So, if you feel up to it, please go ahead
