### ISSUE TITLE
static member vectors_ in HeteroVector class causes linker error

### ISSUE THREAD

**Issue by wtom76** [hosseinmoein/DataFrame#37]
Hi,
a decision to have static member defined in .tcc file looks problematic.
If I supress inclusion of HeteroVector.tcc by defining HMDF_DO_NOT_INCLUDE_TCC_FILES, I will get "unresolved external symbols".
If I allow inclusion of HeteroVector.tcc, I will get "already defined" vectors_ in other translation unit.

Is the library supposed to be used in some other way?

**Comment by hosseinmoein** [comment]
@wtom76,
This is fixed now in master

**Comment by wtom76** [comment]
Great. TY
