### ISSUE TITLE
lack of const methods

### ISSUE THREAD

**Issue by wtom76** [hosseinmoein/DataFrame#38]
Hi,
some methods of library classes can be const. Without const it is hard to use const instances/references to const of that classes.

**Comment by hosseinmoein** [comment]
@wtom76,
Can you give me an example of that?

**Comment by wtom76** [comment]
for example (and what I've tried to call from const ref) is _shape()_ could be _shape() const noexcept_ and const versions of _visit(...)_ methods.

**Comment by hosseinmoein** [comment]
I fixed shape() in master

**Comment by wtom76** [comment]
visit(...) const would also be helpfull

usage example

```
// somewhere in header
using DataFrame = hmdf::StdDataFrame<hmdf::DateTime>;
// cpp
ColumnMetrics::ColumnMetrics(const string& col_name, const DataFrame& col_data)
{
	const pair<size_t, size_t> shape = col_data.shape();
	MinMaxValidCounter<double, hmdf::DateTime> visitor{};
	col_data.visit<double>(col_name.c_str(), visitor); // will not compile without const version of visit
	valid_count_ = visitor.valid_count();
	null_count_ = shape.first - valid_count_;
	if (valid_count_)
	{
		min_ = visitor.min();
		max_ = visitor.max();
	}
}

```

Thank you!

**Comment by hosseinmoein** [comment]
Yeah, that's a bit messy, because the visitors could potentially modify data and you do not want to prevent that. I have to think about it.

**Comment by hosseinmoein** [comment]
@wtom76 ,
I added the const versions to master. Please, take a look
The reason as I mentioned in your pull request is that I don;t want to repeat code.

Regards,
HM

**Comment by wtom76** [comment]
@hosseinmoein, hi
thank you!
I try to avoid const_cast's but agree with your point.
Also please consider breaking _for_ loop into two where first doesn't need _i < data_s_ check.

Best regards,
Artem

**Comment by hosseinmoein** [comment]
done with the for loops
