### ISSUE TITLE
Adding /bigobj flag in CMakeLists.txt will help

### ISSUE THREAD

**Issue by wtom76** [hosseinmoein/DataFrame#39]
...
if (MSVC)
  **set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /bigobj")**
  add_definitions(-D _CRT_SECURE_NO_WARNINGS)
  add_library(${LIBRARY_TARGET_NAME} STATIC ${${LIBRARY_TARGET_NAME}_SRC})
endif(MSVC)
...
without /bigobj I get linker failure with MSVC 2017

**Comment by hosseinmoein** [comment]
@wtom76,
I don't have a windows environment. But I will look into that

**Comment by hosseinmoein** [comment]
@wtom76 ,
This is also done. see if it helps

**Comment by wtom76** [comment]
TY
