### ISSUE TITLE
Need any help with refactoring and other simple stuff ?

### ISSUE THREAD

**Issue by D-K-E** [hosseinmoein/DataFrame#4]
Hi,
I am somewhat experienced in python, but I have limited experience in c++. 
However the project really seems interesting and I want to contribute. 
Is there any work around for a newbie maybe like writing docs, refactoring, 
or writing simple functions, implementing simple interfaces etc.
Any kind of road map and some sort of guide for contribution would be really good.

**Comment by hosseinmoein** [comment]
I appreciate all contributions.
I suggest you start with going through the doc in `DataFrameDoc.docx` and `datasci_tester.cc`.
-- Suggest any interface/functionality that you think is missing.
-- Contribute any algorithm you think is worth adding.
-- Introduce other people to the codebase
-- ...

**Comment by D-K-E** [comment]
Hi,
I looked at the tester and `DataFrameDoc`. I think I get the basic structure of the interface. It would be great if there is some kind of tutorial to showcase some of the functionality. Maybe something in `jupyter notebook`. They support c++ kernels as far as I know. I can try to come up something if you are interested.

**Comment by hosseinmoein** [comment]
Yes, that sounds good. Go ahead

**Comment by justinjk007** [comment]
@D-K-E It will be great if you can add doxygen!
