### ISSUE TITLE
parse .sas7bdat file

### ISSUE THREAD

**Issue by daliuzhen1** [hosseinmoein/DataFrame#41]
Sas7bdat is a format of sas file.  Data scientist need read it directly. and put them into dataframe
Please see the following link
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sas.html

**Comment by hosseinmoein** [comment]
I am traveling for a few weeks. I will look in a few weeks

**Comment by daliuzhen1** [comment]
OK, have a nice trip
