### ISSUE TITLE
sort by multi columns and ascending or descending order

### ISSUE THREAD

**Issue by BCSN000001** [hosseinmoein/DataFrame#42]
I am wondering whether the library can be improved to handle more sort algos.
Many many tks.
Currently, data frame can be sorted by only one column. In many circumstances, we want to sort the data frame by col1 first in ascending order, and then by col2 secondly in descending order, and then  blabla...
May I know whether this request can be implemented? 

:-)

**Comment by hosseinmoein** [comment]
Yes, this sounds like a useful enhancement. I am traveling currently, but will look into it in the next several days

**Comment by BCSN000001** [comment]
Another better sort solution is to compute the sorted indices first and then apply to each columns. Currently, when sorting each column, a multimap have to be constructed. If we can store the sorted indices in advance, then what we do to sort a column is just to re-assign the column values by the sorted indices in just O(n) time. It must be more efficient.

**Comment by BCSN000001** [comment]
> Yes, this sounds like a useful enhancement. I am traveling currently, but will look into it in the next several days

Another better sort solution is to compute the sorted indices first and then apply to each columns. Currently, when sorting each column, a multimap have to be constructed. If we can store the sorted indices in advance, then what we do to sort a column is just to re-assign the column values by the sorted indices in just O(n) time. It must be more efficient.

**Comment by hosseinmoein** [comment]
I will look. Too,may tings to do, so little time is available.

**Comment by hosseinmoein** [comment]
@BCSN000001,
I rearranged sorting logic to improve performance. When I get another chance, I will implement multi-column sort.

**Comment by hosseinmoein** [comment]
I also implemented multi-column sorting.
Now you can specify up to 5 columns. Also independently specify ascending/descending for each column.
