### ISSUE TITLE
Input/output formats

### ISSUE THREAD

**Issue by jfnavarro** [hosseinmoein/DataFrame#44]
Hi! 

It would be nice to support reading and writing from/to the standardised "comma separated" and "tab separated" formats used in R and Pandas (Python). 

Great work!

**Comment by hosseinmoein** [comment]
I do support reading/writing in CSV and JSON formats. But they are not exactly the same specs as Pandas or R. That is because C++ is strongly typed and needs more info. I have also added more info for efficiency (e.g. number of items in a column). 
But I am open to suggestions and contributions.

Best,
HM

**Comment by jfnavarro** [comment]
Yes, I understand since you allow columns of different types that it is hard to generalise the parsing.  I do however think that the most common scenario is to deal with data frames where all the columns have the same type (either int or double). This would simplify the parsing. 

I am just playing a bit with the library, trying to see if it fullfils what I need to integrate it in one of my project. 

I think a get_row() method similar to get_column() when one passes the row ID (not index) and gets the whole row as a vector would be nice. Of course this would be easier when all the columns are of the same type. Should I add this a new feature request?

**Comment by hosseinmoein** [comment]
There is already a `get_row()` method that returns a hetero vector for a given row index.
What do you mean by a row id? There is no "id" or "name" associated with a row, because potentially there could be billions of rows.

**Comment by jfnavarro** [comment]
Maybe I misunderstood but 
`get_row(size_type row_num, const std::array<const char *, N> col_names) const;`
Takes the row number as an argument and by that I understand the row index (1 - num_rows) instead of the actual row ID. In my case I use strings as row and column ids (this is quite common when working with data-frames).

**Comment by hosseinmoein** [comment]
Yes, row number is from `[0 - num_rows)`.
As I mentioned above there is no ids or strings associated with a row. This is designed to work with large to extremely large data sets. There could be billions of rows (or more), I cannot practically (and efficiently) associate a unique string/ID with each row.
But columns are identified with strings.

**Comment by daliuzhen1** [comment]
> But they are not exactly the same specs as Pandas or R. That is because C++ is strongly typed and needs more info.

I have a suggestion. 
Most data source already has column type such as database. But csv json does not have.
About csv I think we can calc the column type based on the first 100 row.
The Strategy is string > double > int
For example. If the column first 100 row contains a string. The column type is string.
About store the data, could we use std::any or other technology?
