### ISSUE TITLE
Drop shared option for Windows, porting with conan supported.

### ISSUE THREAD

**Issue by yssource** [hosseinmoein/DataFrame#47]
Hi, @hosseinmoein 
I was porting this project to be supported with [conan-center-index](https://github.com/conan-io/conan-center-index/pull/542) .

But , I was trying to access a symbol which wasn't exported, and DataFrame project doesn't support __declspec(dllexport)/__declspec(import). Even if I force CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON it won't work.

Actually, I have very little knowledge about how to compile with Visual Studio.
So, please take a look into https://github.com/conan-io/conan-center-index/pull/542, and consider to support it with conan in the next release.
Thanks.

**Comment by hosseinmoein** [comment]
My knowledge of VC++ compiler is also limited (And I have no access to one). DataFrame was mostly ported to VC++ by @justinjk007. 
What is Conan center index? What is the advantage of porting to Conan?
Also, @MyDataModels added `conanfile.py` to do the Conan compilation. Have you looked at that? It is in the root directory of DataFrame

**Comment by hosseinmoein** [comment]
I looked at ` conan-io/conan-center-index#542`. So have you been able to successfully port to Conan? If so, do you have a pull request that passes AppVoyer and Travis CI?

**Comment by yssource** [comment]
-   [Coan](https://docs.conan.io/en/latest/introduction.html) is a decentralized package manager, the alternative is [microsoft/vcpkg](https://github.com/microsoft/vcpkg)
But, I prefer conan to vcpkg.

-   [conan-center-index](https://github.com/conan-io/conan-center-index/wiki) is maintained by the core members of Conan.

-   Actually, I have successfully compiled DataFrame by AppVoyer and Travis CI under **some platforms and compilers**.
But, conan-center-index uses the [jenkins tools](https://jenkins.io/) to do CI/CD jobs and it has more requirements of its own. It needs the package to be compiled by most compilers of various platforms, according the option settings in the conanfile.py.

-   Currently, I'm afraid it is not a good way to create a Conan package for DataFrame by mydatamodels.

-   By the way, I think I may know why my PR fails to compile with Visual Stuio.

> My recipe offers shared/static library option, by DataFrame only offer an unique type per platform

    # Build the library
    if (UNIX)
      add_library(${LIBRARY_TARGET_NAME} SHARED ${${LIBRARY_TARGET_NAME}_SRC})
    endif(UNIX)
    
    if (MSVC)
      add_definitions(-D _CRT_SECURE_NO_WARNINGS)
      add_library(${LIBRARY_TARGET_NAME} STATIC ${${LIBRARY_TARGET_NAME}_SRC})
    endif(MSVC)
    
    if (MINGW)
      add_library(${LIBRARY_TARGET_NAME} STATIC ${${LIBRARY_TARGET_NAME}_SRC})
    endif()

Personally, I think there are two ways to figure out this problem.

1.  As suggested by @uilianries Request such support to the upstream

    support __declspec(dllexport)/__declspec(import).

1.  Keep the SHARED/STATIC as what was in upstream's Cmakefiles.txt

    config the SHARED/STATIC option in my conanfile.py, according to different platforms respectively.

-  Finally, please keep this ticket opened until conan-center-index merged my PR. I will try to modify my PR in the following days.

Thanks.

**Comment by yssource** [comment]
Oh, no no no.
It should not change any value for `Shared` option in conanfile.py. Since the conan package-id is determined by its settings, options and requirements.

So, I think it is still to have `__declspec(dllexport)/__declspec(import)` supported.

**Comment by hosseinmoein** [comment]
Thanks. I will keep the issue open, until it is resolved

**Comment by yssource** [comment]
I'm going to create a Conan package for DataFrame.
Would you make a next release?

**Comment by yssource** [comment]
If [conan-center-index](https://github.com/conan-io/conan-center-index/pull/542) merged my PR with your new release (v1.7.0), the user would simplify call 
`conan create dataframe/1.7.0@`

By the way, currently the conanfile.py is not required, it should be removed.

**Comment by hosseinmoein** [comment]
ok, I will remove the `conanfile.py`
I don't know yet when I would make the next release. But it should be with a month or so

**Comment by yssource** [comment]
conan creates a package for C++ project based on its release sources.

**Comment by yssource** [comment]
It's OK, I am waiting for your next release, then to create a conan package for it.
