### ISSUE TITLE
How to compile it into js with emscripten?

### ISSUE THREAD

**Issue by liupenghui1982** [hosseinmoein/DataFrame#49]
How to compile it into js with emscripten? 
It is a important factor to fasten use with this C++ version of  Dataframe.

**Comment by hosseinmoein** [comment]
@liupenghui1982, 
That is an interesting question. I imagine turning DataFrame into a usable js would a big project. I found this repo that might help `https://github.com/emscripten-core/emscripten`. There might be other/better ways. I haven't done this before.
I certainly do not have time to do this.
Do you want to take up this project as a contributor?
