### ISSUE TITLE
No definition of `reverse_iterator`

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#50]
Sorry to disturb. I'm trying to learn cpp with your beautiful cpp code.
While I'm reviewing your code of `HeteroView.h`, I've found code `  template<typename T>
    using reverse_iterator = typename VectorView<T>::reverse_iterator;`.
However in file `VectorView.h`, there doesnot exist a definition of `reverse_iterator`, am I misunderstanding something ?

**Comment by hosseinmoein** [comment]
Yes. I forgot to define that. Probably, because I never needed it. But for completeness, I should define it.
