### ISSUE TITLE
Mean Visitor overflows with large vectors

### ISSUE THREAD

**Issue by kunaltyagi** [hosseinmoein/DataFrame#51]
https://github.com/hosseinmoein/DataFrame/blob/2fc08c742d2bffa59251aaf139d00755ff404655/include/DataFrame/DataFrameStatsVisitors.h#L60

Since mean is not calculated incrementally, it can overflow easily specially on timestamps.

There's a one pass StatsVisitor which works, but also computes other higher order stats. Is it possible to specify which stats are required in the stats visitor? Or specify online mode for mean visitor?

**Comment by hosseinmoein** [comment]
When I come back I can add a step count to mean. But alternatively you can use a ‘MeanVisitor<long double>’. You have to staticly cast it back to ‘double’ when getting the result.

It will be a bit slower but not much worse than a mean with step count

**Comment by kunaltyagi** [comment]
I wrote a iterative mean visitor for myself from the StatsVisitor, so that worked out ok.

> When I come back I can add a step count to mean

Speaking of step count, there's another subtle bug that I narrowly missed by using int instead of float:
* for large number of rows (say 100 thousand, 10^5)
* with values within 2-3 orders of magnitude (10^3 spread)

It could have resulted in lost precision since float only has ~7 digits of precision. A `SafeMeansVisitor` might be helpful since this wouldn't be an uncommon usage (people using float when it might be better to use int_64 or double)
