### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by develooper1994** [hosseinmoein/DataFrame#52]
Do you think give gpu support? at least cuda. You can have gpu support by using existing libraries like dlib or something else if you don't want to struggle with raw cuda.

**Comment by hosseinmoein** [comment]
That is a good suggestion. Currently, I do not have the bandwidth to do this. Do you think you are up to contributing and implementing this? Or at least give me a pull requesting for the starting point?

Best

**Comment by develooper1994** [comment]
I like your project. I want to but I am currently working on my master thesis that denoises signal.
What is the purpose of project? Portable? easy to use? Fast?

**Comment by hosseinmoein** [comment]
The purpose is partially explained in the doc (https://github.com/hosseinmoein/DataFrame/blob/master/docs/DataFrameDoc.pdf) under "Motivation" header.

But basically:

1. Add to the badly needed C++ ecosystem
2. Create a data frame similar to Pandas that can handle very large data sets, efficiently and be scaleable
3. Add a badly needed tool to field of financial back-testing and alpha/risk modeling for environments that are purely in C++

**Comment by develooper1994** [comment]
One more thing. There is a Nim language. You should look at.
