### ISSUE TITLE
Query interface examples

### ISSUE THREAD

**Issue by schmitts** [hosseinmoein/DataFrame#54]
Could you please add examples on how to query/select? E.g. how does a pandas query like below look in DataFrame?

```
df_filtered = df[df.something > 5]
```

**Comment by hosseinmoein** [comment]
The equivalent to that, in DataFrame, is either of the following methods:
```
get_data_by_sel()
get_view_by_sel()
```
The documentation for them is here:
https://github.com/hosseinmoein/DataFrame/blob/master/docs/DataFrameDoc.pdf

There are examples in the tester file here:
https://github.com/hosseinmoein/DataFrame/blob/master/test/dataframe_tester.cc#L2748
and here:
https://github.com/hosseinmoein/DataFrame/blob/master/test/dataframe_tester.cc#L2826

There are similar examples to your questions in the tester file

**Comment by yegorrr** [comment]
how can i do something like
`df["price_usd"]=df["price"]*df["fx_rate"]`
or
`df["x"]+=constant`
for each timestamp(including missing data), ie something like a visitor but for rows instead of columns

**Comment by hosseinmoein** [comment]
There are a couple of different ways:
Look at consolidate()
You can write your own visitor which is simple
Or you can manually do it with a loop

**Comment by yegorrr** [comment]
thanks, consolidate is probably what i was looking for.

another question, assume i'm adding last trade pices of some asset in real time and i'm only interested in its current price and moving average over x seconds. what would be the most efficient way:
1) store all trades and timestamps as they arrive in data frame and on each insert call get_data_by_sel() filtering all trades over last x seconds and averaging that data
2) create a separate structure, kind of a queue that stores only data over the last x seconds  - each insert may pop an arbitrary amount of elements from the queue - from 0 to N. assuming all data is sorted by timestamps, this would be as efficient as #1
3) something else?

**Comment by hosseinmoein** [comment]
If you don’t need all the data, why store it? In that case something like 2 is better
