### ISSUE TITLE
Concat two dataframes

### ISSUE THREAD

**Issue by m4ce** [hosseinmoein/DataFrame#55]
I was looking for something similar to pd.concat but I was unable to. Is there any way to achieve that? If not, what would you suggest as an alternative?

**Comment by hosseinmoein** [comment]
I don't exactly have concatenate. I was planning to add it in a week or so.
But I have join. I am not sure if that helps you.
Please look at
```
join_by_index()
join_by_column()
join_policy
``` 
in the document. The examples start from here https://github.com/hosseinmoein/DataFrame/blob/master/test/dataframe_tester.cc#L927

**Comment by m4ce** [comment]
@hosseinmoein, it's not really a join here but more like a concat. I need to add more rows to an existing dataframe. I will wait for you to develop a concat then ;) Look forward to! Keep the good work up, amazing project.

**Comment by hosseinmoein** [comment]
Sounds good.
Also, you may want to look at 
```
append_index()
append_column()
```

**Comment by hosseinmoein** [comment]
@m4ce,
I added 
```
concat()
self_concat
```

**Comment by m4ce** [comment]
@hosseinmoein - that was fast. I will try it out and report back if there are any issues!
