### ISSUE TITLE
Undefined reference to `hmdf::HeteroVector::clear()'

### ISSUE THREAD

**Issue by Trento89** [hosseinmoein/DataFrame#56]
When I tried to smoke test my code, I found that even trying to declare a dataframe resulted in an error at compile time.  Am I missing a header file?

I'm running Debian 10 and am not using an IDE - I'm simply using g++ (I will create a Makefile once my code makes it past the smoke test).  Below is the command I am using and the corresponding error.

**username@system:/tmp/smoke_test$ g++ test_dataframe.cpp -I DataFrame/include/ -std=gnu++17 -o test_dataframe
/usr/bin/ld: /tmp/ccjU2Oy0.o: in function `hmdf::HeteroVector::~HeteroVector()':
test_dataframe.cpp:(.text._ZN4hmdf12HeteroVectorD2Ev[_ZN4hmdf12HeteroVectorD5Ev]+0x14): undefined reference to `hmdf::HeteroVector::clear()'
collect2: error: ld returned 1 exit status**

[test_dataframe.cpp.txt](https://github.com/hosseinmoein/DataFrame/files/4270364/test_dataframe.cpp.txt)

**Comment by hosseinmoein** [comment]
You are getting this error because you are not linking with the DataFrame library.
DataFrame is _almost_ a header-only project. But there are some amount of code that has to be compiled into a library and then linked with.

If you follow the build instructions with `cmake` in the README section, it will build the DataFrame library and test executables.  I would recommend that. After you build it, you can link with the library when building your example.
If you rather doing the whole thing in your own makefiles, take a look at my private make file in https://github.com/hosseinmoein/DataFrame/tree/master/src to get some guidelines.

**Comment by Trento89** [comment]
Thank you for your reply.  I followed the instructions for installing the library using cmake, and it now appears that I was successful in installing the library.  However, I'm still getting the undefined reference errors when I try to compile the .cpp file using g++.  For the purpose of just getting this very trivial program to compile and successfully instantiate the StdDataFrame (and thus passing the smoke test), is there a specific change that I should be making to the libraries that I am #including or to the arguments I'm passing to g++ in the Bash terminal?

**Comment by hosseinmoein** [comment]
There is nothing wrong with your `#include`. You are not failing at compiling your program. You are failing at linking your program. That means you are failing to link to DataFrame library to resolve all the external symbols.
Now that you have successfully made the DataFrame you have to link with its library on your compiling command line. So change your command line to something like
```
g++ test_dataframe.cpp -I DataFrame/include/ -std=gnu++17 -Bstatic  -L<Path to where DataFrame Library is> -lDataFrame -lpthread -ldl -lm -lstdc++ -o test_dataframe
```
That is a typical command line to compile and link any C++ program using a library, whether it is a very simply program or very complicated.

Hope that helps

**Comment by Trento89** [comment]
It works!  Thank you!

**Comment by Trento89** [comment]
I'm sorry to bother you with this again, but I'm getting error messages again when I try to compile from multiple source files (and use header files) and then link the objects together into an executable.  Is the problem the Makefile, the .cpp files, or the header file?  And shouldn't the **#pragma once** directive prevent the **read_data.h** file, as well as the library headers, from being read multiple times which is what leads to multiple reference errors?

I've tried making multiple changes to the **#include** directives in the .cpp files and the header files and nothing seems to have worked.  What am I missing here?

[main.cpp.txt](https://github.com/hosseinmoein/DataFrame/files/4303762/main.cpp.txt)
[Makefile.txt](https://github.com/hosseinmoein/DataFrame/files/4303763/Makefile.txt)
[read_data.cpp.txt](https://github.com/hosseinmoein/DataFrame/files/4303764/read_data.cpp.txt)
[read_data.h.txt](https://github.com/hosseinmoein/DataFrame/files/4303765/read_data.h.txt)
[sample_data.csv.txt](https://github.com/hosseinmoein/DataFrame/files/4303766/sample_data.csv.txt)
![shell_screenshot](https://user-images.githubusercontent.com/50342484/76169859-de1ee280-6152-11ea-9d98-d17b6e1fc4f3.png)

**Comment by hosseinmoein** [comment]
I can see a few problems, but you may have more.
1. You have defined `DataFrame_t` multiple times
2. In your makefile, when compiling source code into object file you are also linking with DataFrame library. That might be the cause of your multiple definitions
3. Your DataFrame library location seems to be incorrect
4. You have not built and link with the boost library?

It is hard to debug remotely.
Instead of I pointing out mistakes in a few lines, I suggest you read up on compilers and makefiles and understand the stages a compiler goes through to get a text source file to a binary executable. This way, you will have a much broader view of what is going on.

**Comment by Trento89** [comment]
I accidentally posted a later iteration of what I was working with after a series of trial-and-error attempts, and I apologize for loading the wrong file there.  I corrected the problems you mentioned, but I'm still getting errors and I'm not sure why this keeps happening.

I understand that the C/C++ compiling process consists of: preprocessing, where the compiler follows preprocessing directives such as expanding macros and including libraries and header files; compiling the C/C++ files (while following preprocessing directives) into assembly language code; assembling the assembly language code into binary object files; and linking the binary object files into a binary executable that contains direct instructions that the computer can then execute.  The Makefile contains a series of instructions to the compiler so that for a large program whose source code is spread across (for example) 20 files, the programmer does not have to manually type 20 different instructions into the shell to create the object files before linking them together into the binary executable.

So far the only way that I have stopped getting errors has been to #include **read_data.cpp** from the **main.cpp** file, but I know that this is a sloppy kludge and considered very bad style; I also know that such a "solution" will break as soon as I add more .cpp files.

What I'm having trouble understanding now, after having applied the changes, is why I'm getting a multiple definition error for **hmdf::gen_bernoulli_dist()** when 1) the #include directive to use the library file containing it exists only in the **read_data.h** file and nowhere else and 2) the header file **read_data.h** has a **#pragma once** directive.  I'm also not sure why there is an undefined reference error for **hmdf::HeteroVector::HeteroVector()** when the header file has an explicit **#include <DataFrame/Vectors/HeteroVector.h>** directive on Line 16.

What did I enter incorrectly for the DataFrame library location?  I thought the Makefile was pointing to the location where it's installed.

Any help you could provide here would be much appreciated.  Not being able to compile the code due to these errors seems to be the main bottleneck in my project.

[main.cpp.txt](https://github.com/hosseinmoein/DataFrame/files/4307351/main.cpp.txt)
[Makefile.txt](https://github.com/hosseinmoein/DataFrame/files/4307352/Makefile.txt)
[read_data.cpp.txt](https://github.com/hosseinmoein/DataFrame/files/4307353/read_data.cpp.txt)
[read_data.h.txt](https://github.com/hosseinmoein/DataFrame/files/4307354/read_data.h.txt)
[sample_data.csv.txt](https://github.com/hosseinmoein/DataFrame/files/4307355/sample_data.csv.txt)
![shell_screenshot](https://user-images.githubusercontent.com/50342484/76226729-a5cfe080-61f4-11ea-8501-669fa7f1c3dd.png)

**Comment by hosseinmoein** [comment]
Your understanding of the compile process is incorrect. Also, your understanding of what role header files play is incorrect. I still suggest you put some time aside to read up on them.

I still see problems:
1. The location of DataFrame library is specified as `/usr/local/include/DataFrame/`. I highly doubt that is where the library is. And if it is there somehow, it shouldn't be.
2. You are still specifying and linking with the library when compiling object files.

This is a typical line for compiling an object file
```
/usr/bin/g++ -g -I. -I../../include -DP_THREADS -D_POSIX_PTHREAD_SEMANTICS -std=c++17 -c ../test/dataframe_tester.cc -o ../obj/Linux.GCC64D/dataframe_tester.o
```
And this is a typical line to link and executable
```
/usr/bin/g++ -o ../bin/Linux.GCC64D/dataframe_tester ../obj/Linux.GCC64D/dataframe_tester.o  -Bstatic -L../lib/Linux.GCC64D -lDataFrame -lpthread -ldl -lm -lstdc++
```

**Comment by Trento89** [comment]
Thank you.  I will try to implement your suggestions.

If I followed your installation instructions correctly, where should the library be located on a Linux machine?

**Comment by hosseinmoein** [comment]
CMake decides dynamically. But I imagine in your system it would somewhere under `/usr/local/lib` probably under `DataFrame`. Also look at `/usr/lib`.

**Comment by Trento89** [comment]
I based the path on the output of the installation process.  I followed your installation instructions to the letter (or at least I think I did) and the locations are shown below.

![screenshot](https://user-images.githubusercontent.com/50342484/76231776-1a5a4d80-61fc-11ea-8765-75f167ef0aba.png)

**Comment by Trento89** [comment]
> Your understanding of the compile process is incorrect. Also, your understanding of what role header files play is incorrect. I still suggest you put some time aside to read up on them.
> 
> I still see problems:
> 
>     1. The location of DataFrame library is specified as `/usr/local/include/DataFrame/`. I highly doubt that is where the library is. And if it is there somehow, it shouldn't be.
> 
>     2. You are still specifying and linking with the library when compiling object files.
> 
> 
> This is a typical line for compiling an object file
> 
> ```
> /usr/bin/g++ -g -I. -I../../include -DP_THREADS -D_POSIX_PTHREAD_SEMANTICS -std=c++17 -c ../test/dataframe_tester.cc -o ../obj/Linux.GCC64D/dataframe_tester.o
> ```
> 
> And this is a typical line to link an executable
> 
> ```
> /usr/bin/g++ -o ../bin/Linux.GCC64D/dataframe_tester ../obj/Linux.GCC64D/dataframe_tester.o  -Bstatic -L../lib/Linux.GCC64D -lDataFrame -lpthread -ldl -lm -lstdc++
> ```

Just to clarify, is the issue now solely the Makefile, or are there still problems with the .cpp files and the **read_data.h** header file?

**Comment by hosseinmoein** [comment]
From my cursory look, there is nothing wrong in the source code

**Comment by Trento89** [comment]
Thank you.  This clarification will save me a lot of time!

**Comment by yegorrr** [comment]
i'm compiling under MSVC 2022 with DataFrame.lib (i got it via vcpkg) but it gives me "Undefined reference to `hmdf::HeteroVector::clear()" error

**Comment by hosseinmoein** [comment]
Most probably because when you are linking your executable, you are not linking with the DataFrame library

**Comment by yegorrr** [comment]
other than DataFrame.lib?

**Comment by yegorrr** [comment]
> other than DataFrame.lib?

there must be something wrong with vcpkg, i build everything from github repo and now it works fine
