### ISSUE TITLE
Any plan to support the normal csv format?

### ISSUE THREAD

**Issue by qingtiandalaoye** [hosseinmoein/DataFrame#57]
I checkout the csv in testcases, seems all columns store by lines,  it is hard to interaction with R or excel or Pandas.

**Comment by hosseinmoein** [comment]
I confess that I spent the least amount of time on the parts that read/write from files in any format.
The `csv` format is never going to be exactly like Excel or Pandas, since I have to know the types (it is C++).
The reason I did it line oriented way because it was the easiest and most efficient way. I also record the number of items in each column so memory allocation is done efficiently. 
I would like to find a contributer to enhance upon that.

**Comment by qingtiandalaoye** [comment]
maybe we can learn readcsv from FLink, here are some codes:
`
env.readCsvFile(filePath1)
                .fieldDelimiter(",")
                .ignoreFirstLine()
                .includeFields(true, true, true, true, true, true)
                .pojoType(FuturesBarCsv.class, "datetime", "open", "high", "low", "close", "volume")
.........................
`

and the FuturesBarCsv is a POJO as this, which we can define a struct in C/CPP :
`
@Data
public class FuturesBarCsv {
    public String symbol;
    public String datetime;
    public Long timestamp;
    public Double open;
    public Double high;
    public Double low;
    public Double close;
    public Long volume;
`

**Comment by Trento89** [comment]
I wrote this Python program to transpose CSV files for hmdf compatibility.  Things like filepaths, column names, and data types are hardcoded, but they can be changed easily.
[transpose_csv_for_hmdf.py.txt](https://github.com/hosseinmoein/DataFrame/files/4366513/transpose_csv_for_hmdf.py.txt)

**Comment by Trento89** [comment]
Actually, if you have multiple .csv files in a directory this version will let you iterate through all of the files in the directory.
[transpose_csv_for_hmdf.py.txt](https://github.com/hosseinmoein/DataFrame/files/4366625/transpose_csv_for_hmdf.py.txt)

**Comment by hosseinmoein** [comment]
That's very cool. If you can generalize this for usual types (e.g. double, int, unsigned int, ...) and also not hard coding column names you can give me a pull request.
thanks,

**Comment by swilson314** [comment]
I suspect the lack of file format support may be a stumbling block for many wanting to use your library, i.e. there is no good way to get data into it. You could use Apache arrow to read csv, arrow and parquet files. For example, there is a TableReader object that specifically reads csv, determines the column types and everything you need.

**Comment by hosseinmoein** [comment]
You are right. As I mentioned above reading/writing files have been neglected in this library.
I have to find time to implement arrow, regular csv, parquet...

**Comment by hosseinmoein** [comment]
@qingtiandalaoye , @Trento89 , @swilson314 ,

I added the `io_format::csv2` which prints the DataFrame very similar to Pandas csv format. In other words `io_format::csv2` is the transpose of `io_format::csv`.
Please see documentation and examples here

https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/io_format.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/read.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/write.html
