### ISSUE TITLE
I don`t know how to install it in windows Clion

### ISSUE THREAD

**Issue by suchmors** [hosseinmoein/DataFrame#58]
i`ve just downloaded the file but i don`t know how to install or lead it in  
i`ve tried to run the project in Clion
then i got a floder named cmake-build-debug with bin
after entered into bin,i ran the  file dataframe_performance.exe
however it crashed at once and said 

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

so would you please tell me how install it in windows

**Comment by hosseinmoein** [comment]
`dataframe_performance` loads a very large number of items into DataFrame. It has a very large memory footprint. If your system memory cannot tolerate that, you should edit `dataframe_performance.cc` and reduce the number of items being generated.
Currently it creates a datum for each second between `01/01/1970` and `08/15/2019` for 3 columns. You can shorten that interval.

**Comment by suchmors** [comment]
> `dataframe_performance` loads a very large number of items into DataFrame. It has a very large memory footprint. If your system memory cannot tolerate that, you should edit `dataframe_performance.cc` and reduce the number of items being generated.
> Currently it creates a datum for each second between `01/01/1970` and `08/15/2019` for 3 columns. You can shorten that interval.

thanks,but my main question is that I`m not able to import it in into my project,
my enviorment is  Clion, and I write the Cmakelists.txt like this:
cmake_minimum_required(VERSION 3.15)
project(MulThreadTest2)

set(CMAKE_CXX_STANDARD 17)
set(INC_DIR "C:\\Program Files (x86)\\DataFrame\\include")
set(LINK_DIR "C:\\Program Files (x86)\\DataFrame\\lib")

include_directories(${INC_DIR})

link_directories(${LINC_DIR})

link_libraries(DataFrame)

add_executable(MulThreadTest2 main.cpp)

target_link_libraries(MulThreadTest2 DataFrame)

but if always return me the error :
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lDataFrame
collect2.exe: error: ld returned 1 exit status

**Comment by hosseinmoein** [comment]
I am not familiar with Clion that much.
But
Have you been able to successfully make/install DataFrame library, by following the CMake  instructions in readme?
You specify the lib directory for DataFrame as `C:\Program Files (x86)\DataFrame\lib`. Do you see the library in that directory? Did CMake install it there?

**Comment by suchmors** [comment]
> I am not familiar with Clion that much.
> But
> Have you been able to successfully make/install DataFrame library, by following the CMake instructions in readme?
> You specify the lib directory for DataFrame as `C:\Program Files (x86)\DataFrame\lib`. Do you see the library in that directory? Did CMake install it there?

yes,but...
what i can see in lib are two files,one of those is named pkgconfig,and the other is libDataFrame.a
I was trying to install it by cmake in your ways , but it dosen`t work.
for example:
**I download the files and take it in C:\files\
then in cmd.exe**
C:\Windows\system32>cd C:\files\DataFrame-master

C:\files\DataFrame-master>mkdir Debug

C:\files\DataFrame-master>cd Debug

C:\files\DataFrame-master\Debug>cmake -DCMAKE_BUILD_TYPE=Debug
**CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "C:/files/DataFrame-master/Debug" does not app
ear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.**


so i try another way 
cmake.exe -G "MinGW Makefiles"
mingw32-make

and the result became that

**Comment by hosseinmoein** [comment]
You are missing the `..` at the end of cmake command
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
```
