### ISSUE TITLE
C2061 compile error in DataFrame.h

### ISSUE THREAD

**Issue by swilson314** [hosseinmoein/DataFrame#62]
I downloaded the source and ran cmake to generate VS 2017 project files. ALL_BUILD ran fine except the one error shown below in the text and screenshot. The error is fixed if I change the diff_func return type from size_type to DataFrame::size_type. Just wanted to verify this is correct?

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2061	syntax error: identifier 'size_type'	dataframe_tester_2	f:\dev\dataframe-master\include\dataframe\dataframe.h	277	

![image](https://user-images.githubusercontent.com/24533910/77970584-6a7b7b80-72a1-11ea-98a3-76511766a826.png)

**Comment by hosseinmoein** [comment]
Hmm, I thought I already did that. Yeah, that should fix for ms compilers

**Comment by hosseinmoein** [comment]
I just fully corrected its syntax for Windows.
Unfortunately, I don't have access to a windows development environment. I have to go through Appveyor :-)

**Comment by swilson314** [comment]
Thanks. If this becomes part of our ML pipeline I’ll test it frequently for you ;)
