### ISSUE TITLE
Help with installation on Windows

### ISSUE THREAD

**Issue by YannickLecroart** [hosseinmoein/DataFrame#66]
Hi, 

I read the instructions in the Readme section but I do not know what to do at step 4 in the command prompt

step 1) mkdir [Debug | Release]
step 2) cd [Debug | Release]
step 3) cmake -DCMAKE_BUILD_TYPE=[Debug | Release] ..
step 4) make
step 5) make install

I have managed to generate build files as you can see here.

![df](https://user-images.githubusercontent.com/43994829/79764932-49e59500-8326-11ea-9b09-9c92323d6938.jpg)

But the "make" or "make install" do not work from the command line.

![df2](https://user-images.githubusercontent.com/43994829/79765114-80231480-8326-11ea-9fa1-e2ef8c8f7c22.png)

I am a bit confused on what I should do next to add your library to my Visual Studio Community C++ project to be able to use your dataframe class to manipulate tabular data from a CSV file. 

Thanks in advance. 

Regards,

**Comment by hosseinmoein** [comment]
My French is rusty. But it sounds like you do not have make installed.
Look at these for how to install make:
https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows
https://stat545.com/make-windows.html

or you may have a better way of doing that. I am not an expert in Windows.

**Comment by YannickLecroart** [comment]
thanks for the feedback, I have now installed make via Chocolatey on Windows it says "no targets specified and no makefile found. Stop". What should I do next from there?

![image](https://user-images.githubusercontent.com/43994829/79770683-098a1500-832e-11ea-8285-d9f985b3000f.png)

**Comment by hosseinmoein** [comment]
Did you do this `cd [Debug | Release]`

**Comment by YannickLecroart** [comment]
Yes I guess as you can see in the attached picture. 

![image](https://user-images.githubusercontent.com/43994829/79792516-55998180-834f-11ea-91fd-063aca04e2ed.png)

I am sorry to bother you like this but there must be something I do not get with the procedure.

**Comment by hosseinmoein** [comment]
Can you remove the `Debug` directory and do the cmake process from the beginning now that you have make?

Also, I think you are getting warning re/ `CMAKE_BUILD_TYPE` because your visual studio doesn't have debug versions of the libraries. This may or may not be a separate issue.
If removing the `Debug` directory approach doesn't work. try building it in `Release` mode.
Basically, when you run `cmake`, you should have a file named `Makefile` in [Debug |. Release] directory.

**Comment by YannickLecroart** [comment]
I removed the Debug folder and started from scratch but to no avail. It says that the filed have been Added to the recently created Debug folder but the make commands still gives the same error message.

![image](https://user-images.githubusercontent.com/43994829/79831320-7c83a200-83a7-11ea-9c12-91b6f15e71b4.png)

I tried the same procedure with the Release but same error message.

![image](https://user-images.githubusercontent.com/43994829/79831851-80fc8a80-83a8-11ea-9c18-85a976cfaac1.png)

**Comment by hosseinmoein** [comment]
I am kind of out of ideas. You have to find somebody familiar with Window's development environment, especially using make in Windows.
I know DataFrame compiles on Windows with the provided cmake files. It compiles on `https://ci.appveyor.com/project/hosseinmoein/dataframe` AppVeyor
Try one more thing
```
make -f <complete Makefile path>
```
Alternatively, you can add all the source files in DataFrame to a visual studio project and do it that way.
But, I think you best bet is to find somebody familiar with Windows

**Comment by hosseinmoein** [comment]
@YannickLecroart ,
look at the log of the AppVeyor here `https://ci.appveyor.com/project/hosseinmoein/dataframe/build/job/rnu25o5gllu03r15`.
They use a different set of commands that you could follow and see if it works
