### ISSUE TITLE
C1001: Internal compiler error

### ISSUE THREAD

**Issue by Razarabi** [hosseinmoein/DataFrame#67]
Hello,

I am currently running into the following errors when including dataframe.h: 

1>D:\cpplib\df\include\DataFrame\Vectors\VectorPtrView.h(59,1): warning C4251: 'hmdf::VectorPtrView<T>::vector_': class 'std::vector<T*,std::allocator<T*>>' needs to have dll-interface to be used by clients of class 'hmdf::VectorPtrView<T>'
1>D:\cpplib\df\include\DataFrame\Vectors\VectorPtrView.h(57): message : see declaration of 'std::vector<T*,std::allocator<T*>>'
1>D:\cpplib\df\include\DataFrame\Vectors\VectorPtrView.h(686): message : see reference to class template instantiation 'hmdf::VectorPtrView<T>' being compiled
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(114,1): warning C4251: 'hmdf::HeteroPtrView::views_': class 'std::unordered_map<const hmdf::HeteroPtrView*,hmdf::VectorPtrView<T>,std::hash<const hmdf::HeteroPtrView *>,std::equal_to<const hmdf::HeteroPtrView *>,std::allocator<std::pair<const hmdf::HeteroPtrView*const ,hmdf::VectorPtrView<T>>>>' needs to have dll-interface to be used by clients of struct 'hmdf::HeteroPtrView'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(113): message : see declaration of 'std::unordered_map<const hmdf::HeteroPtrView*,hmdf::VectorPtrView<T>,std::hash<const hmdf::HeteroPtrView *>,std::equal_to<const hmdf::HeteroPtrView *>,std::allocator<std::pair<const hmdf::HeteroPtrView*const ,hmdf::VectorPtrView<T>>>>'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(119,10): warning C4251: 'hmdf::HeteroPtrView::clear_function_': class 'std::function<void (hmdf::HeteroPtrView &)>' needs to have dll-interface to be used by clients of struct 'hmdf::HeteroPtrView'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(116): message : see declaration of 'std::function<void (hmdf::HeteroPtrView &)>'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(123,10): warning C4251: 'hmdf::HeteroPtrView::copy_function_': class 'std::function<void (const hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>' needs to have dll-interface to be used by clients of struct 'hmdf::HeteroPtrView'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(120): message : see declaration of 'std::function<void (const hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(127,10): warning C4251: 'hmdf::HeteroPtrView::move_function_': class 'std::function<void (hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>' needs to have dll-interface to be used by clients of struct 'hmdf::HeteroPtrView'
1>D:\cpplib\df\include\DataFrame\Vectors\HeteroPtrView.h(124): message : see declaration of 'std::function<void (hmdf::HeteroPtrView &,hmdf::HeteroPtrView &)>'
1>D:\cpplib\df\include\DataFrame\Utils\DateTime.h(178,41): warning C4251: 'hmdf::DateTime::dt_init_': class 'hmdf::DateTime::DT_initializer' needs to have dll-interface to be used by clients of class 'hmdf::DateTime'
1>D:\cpplib\df\include\DataFrame\Utils\DateTime.h(176): message : see declaration of 'hmdf::DateTime::DT_initializer'
1>D:\cpplib\df\include\DataFrame\Utils\FixedSizeString.h(106,11): error C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>D:\cpplib\df\include\DataFrame\Utils\FixedSizeString.h(115,11): error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>D:\cpplib\df\include\DataFrame\Utils\FixedSizeString.h(126,11): error C4996: 'strcat': This function or variable may be unsafe. Consider using strcat_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>D:\cpplib\df\include\DataFrame\Utils\FixedSizeString.h(217,29): error C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>D:\cpplib\df\include\DataFrame\Utils\FixedSizeString.h(230,15): error C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>D:\cpplib\df\include\DataFrame\DataFrame.h(98,1): warning C4251: 'hmdf::DataFrame<I,H>::data_': class 'std::vector<H,std::allocator<_Other>>' needs to have dll-interface to be used by clients of class 'hmdf::DataFrame<I,H>'
1>D:\cpplib\df\include\DataFrame\DataFrame.h(71): message : see declaration of 'std::vector<H,std::allocator<_Other>>'
1>D:\cpplib\df\include\DataFrame\DataFrame.h(2461): message : see reference to class template instantiation 'hmdf::DataFrame<I,H>' being compiled
1>D:\cpplib\df\include\DataFrame\DataFrame.h(100,1): warning C4251: 'hmdf::DataFrame<I,H>::column_tb_': class 'std::unordered_map<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>' needs to have dll-interface to be used by clients of class 'hmdf::DataFrame<I,H>'
1>D:\cpplib\df\include\DataFrame\DataFrame.h(94): message : see declaration of 'std::unordered_map<hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type,std::hash<hmdf::VirtualString>,std::equal_to<hmdf::DataFrame<I,H>::ColNameType>,std::allocator<std::pair<const hmdf::DataFrame<I,H>::ColNameType,std::vector<H,std::allocator<_Other>>::size_type>>>'
1>D:\cpplib\df\include\DataFrame\DataFrame.h(291,1): fatal error C1001: Internal compiler error.
1>(compiler file 'msc1.cpp', line 1532)

I used Cmake GUI to configure and generate the progect and then ran it with VS 2019 to build. I'm unsure if the error is due to my installation procedure or with the library itself. Thank you!

**Comment by hosseinmoein** [comment]
I am not an expert in Windows environment development and don't have access to a Windows environment. But I know that DataFrame compiles and runs on Windows based on AppVeyor.
From your output, I would categorize your problems into 3:

> warning C4251
You can ignore these for now and fix the others below. I think after you fix the other problems, you can run the test executables fine.

> error C4996
As the message suggests define `_CRT_SECURE_NO_WARNINGS` on the compile line to turn off this error

> fatal error C1001: Internal compiler error
I don't know what this is about. But I have a suspicion if you fix the error above, this will also go away
 

I would also look at the AppVeyor log (https://ci.appveyor.com/project/hosseinmoein/dataframe/build/job/p0af31avefk72prg) to see how they compile this which is a bit different from the way you compile it.
