### ISSUE TITLE
Default column types as class template parameters

### ISSUE THREAD

**Issue by zirconium-n** [hosseinmoein/DataFrame#69]
The class is being used like this now:
```
df.make_consistent<int, double, std::string>();
df.get_data_by_idx<int, double, std::string>
df.sort<double, int, double, std::string>
```
Notice all those <int, double ,std::string> repetition. I find these template parameters on methods bloat the code too much. How about put these into DataFrame's template parameters so we can declare a `typedef` and forget these?

**Comment by hosseinmoein** [comment]
I agree that C++ template syntax is awful. But that is C++ currently, and the fact that it is statically typed.
The problem with your suggestion is twofold:
1. It makes it impossible to dynamically add different types to the DataFrame. For example if you are reading data from a file or database, you have to know all the types in advance.
2. It makes assignment operators, joins, addition/subtraction, … super complicated to implement. For example, how do you determine the type of the DataFrame that is the result of a join?
