### ISSUE TITLE
Multiple warnings, preventing successful build for VCPKG with Ninja or MSVC on Windows

### ISSUE THREAD

**Issue by remz1337** [hosseinmoein/DataFrame#73]
Hello,

I am working on a PR for VCPKG to add your library, however I'm not able to complete the VCPKG build since the code triggers multiple warnings (4018, 4244, 4251, 4305 and 4309)

You can see all the warnings with appveyor:
https://ci.appveyor.com/project/hosseinmoein/dataframe/build/job/yb9anjgjd5hc57gn

I'm able to build and test manually, but I need it with VCPKG to officially use it in my project

**Comment by hosseinmoein** [comment]
Thanks for the message.
These warning are in two categories. 
1. Warnings about type mismatches. 
2. Warnings about dll interface.

I have no access to or great expertise in Windows development environment (I am mainly on Linux), So I am not able to provide the dll interfaces. Would you be able, at part of your PR, to do that?

As far as #1. I have to find time to rectify that (it should not be difficult). It would probably take me a week or maybe more.


Best,
HM

**Comment by hosseinmoein** [comment]
@remz1337 ,
It was actually easier than I thought to fix all the warnings except the DLL interfaces warning (C4251).
So the only warnings remaining are the dll interface. I do not have a good solution for them, since I do not have currently access to a windows development environment

**Comment by remz1337** [comment]
Awesome! Thanks, I'll have a look and try to fix the remaining warnings

**Comment by remz1337** [comment]
After digging a bit, it seems fixing this warning would probably require some design thinking so the other suggestion would be to disable these warnings with something like
`#pragma warning(push)
#pragma warning(disable : 4251)
...(code)...
#pragma warning(pop)`

in the few files that trigger it.

Also, there is still one warning about type conversion: 
`C:\Users\rbedardcouture\source\repos\DataFrame\include\DataFrame\Internals\DataFrame_join.tcc(242): warning C4267: 'argument': conversion from 'size_t' to 'const unsigned int', possible loss of data`

If you want, I can help you setup a Windows environment.

**Comment by hosseinmoein** [comment]
Yes, I always wanted to get this to work smoothly on Windows. I really appreciate it, if you can do that.

**Comment by remz1337** [comment]
Great, I suggest we continue this discussion out of Github for the meantime. Join my chatroom when you are available:
http://www.e-chat.co/room/19919991

**Comment by remz1337** [comment]
I have forked the repo and created a branch where I disabled the 4251 warnings [here](https://github.com/remz1337/DataFrame/tree/Remz/DisableW4251)
but I'm still getting some of those:
`...\include\DataFrame/Utils/FixedSizeString.h(313): warning C4305: 'initializing': truncation from 'unsigned __int64' to 'hmdf::VirtualString::size_type'
...\include\DataFrame/Utils/FixedSizeString.h(313): warning C4309: 'initializing': truncation of constant value 
...\include\DataFrame/Utils/FixedSizeString.h(316): warning C4244: '=': conversion from 'unsigned __int64' to 'hmdf::VirtualString::size_type', possible loss of data`
