### ISSUE TITLE
0 Being treated as a missing value

### ISSUE THREAD

**Issue by HA6Bots** [hosseinmoein/DataFrame#74]
Hi,

I noticed that when 0 is in a column and I attempt to use the df.fill_missing function, the 0 gets replaced with -1.
Is there a way to keep the 0?

```
	typedef hmdf::StdDataFrame<unsigned long> MyDataFrame;


	MyDataFrame df;

	std::vector<int> test = { 1, 2, 3, 50, 6, 7, 8, 30};
	std::vector<int> test2 = {0,  1, 52, 21, 72}; // <- 0 here 

	std::vector<unsigned long> ulgvec(8);
	std::generate(ulgvec.begin(), ulgvec.end(), [n = 0]() mutable { return n++; });


	int rc = df.load_data(std::move(ulgvec),
		std::make_pair("int_col", test),
		std::make_pair("int_col_2", test2));

	df.fill_missing<int, 2>({ "int_col", "int_col_2" }, hmdf::fill_policy::value, { -1, -1});


	df.write<std::ostream, unsigned long, int>(std::cout);


```

Thanks

**Comment by hosseinmoein** [comment]
Integral/integer types don’t have a nan representation, so I chose 0 to represent a missing value. I admit, this is very arbitrary.
But what do you expect to happen when you call fill_missing() on an integer  column?

**Comment by HA6Bots** [comment]
It makes sense to use a zero, but is there a way to change the NaN value to a different number? For example I know the maximum possible value for my int column is 100, therefore I can choose a  certain number above this to be the NaN value.

Just an idea something like

df.setNaN(9999);

Thanks

**Comment by hosseinmoein** [comment]
You probably want to use one of the replace() methods
