### ISSUE TITLE
Windows: static lib broken

### ISSUE THREAD

**Issue by SpaceIm** [hosseinmoein/DataFrame#76]
`DataFrame` is more or less broken if static because it unconditionally adds dllexport/dllimport attributes.

For example this macro -found in `VectorPtrView.h`- is wrong for a static lib in Visual Studio:

```c++
#ifdef _WIN32
#  ifdef LIBRARY_EXPORTS
#    define LIBRARY_API __declspec(dllexport)
#  else
#    define LIBRARY_API __declspec(dllimport)
#  endif // LIBRARY_EXPORTS
#else
#  define LIBRARY_API
#endif // _WIN32
```

It should be something like this:

```c++
#if defined(_WIN32) && defined(DATAFRAME_SHARED)
#  ifdef LIBRARY_EXPORTS
#    define LIBRARY_API __declspec(dllexport)
#  else
#    define LIBRARY_API __declspec(dllimport)
#  endif // LIBRARY_EXPORTS
#else
#  define LIBRARY_API
#endif // _WIN32
```

If shared:
- at build time: `LIBRARY_EXPORTS` and `DATAFRAME_SHARED` defined
- at consume time: `DATAFRAME_SHARED` defined

If static: no definition at build and consume time

A better approach would be to rely on `generate_export_header` cmake function: https://cmake.org/cmake/help/v3.0/module/GenerateExportHeader.html
Therefore you would also be able to properly hide symbols with GNU compilers for shared lib.

**Comment by hosseinmoein** [comment]
Thanks, I am currently out of power due to bad weather. When I get power back, I will address this. 
In general I have very little experience with windows environment

**Comment by hosseinmoein** [comment]
@SpaceIm ,
I fixed the issue. You can look at it in https://github.com/hosseinmoein/DataFrame/commit/d5eb0a8ba0a4748135563fe7f7e9fd6bc005745e
thanks
HM

**Comment by SpaceIm** [comment]
@hosseinmoein In this modification, you didn't add any condition based on `BUILD_SHARED_LIB`. For static buid, `HMDF_SHARED` must not be defined (and it doesn't really matter for `LIBRARY_EXPORTS`).
Moreover, `add_definitions` is old CMake, prefer `target_compile_definitions` (PRIVATE for `LIBRARY_EXPORTS` because you don't want that users define this one at consume time, and PUBLIC for `HMDF_SHARED`).

Something like:

```cmake
if(BUILD_SHARED_LIB)
  target_compile_definitions(${LIBRARY_TARGET_NAME} PRIVATE LIBRARY_EXPORTS PUBLIC HMDF_SHARED)
endif()
```

**Comment by hosseinmoein** [comment]
The problem is I don't have access to a windows development environment and have to rely on Appveyor which is almost impossible to resolve things.
But it seems that the DataFrame code would not work in static windows compilation. I get a lot of errors when compiling DateTime.cc and .h. That is why I left the compilation to be shared unconditionally.
