### ISSUE TITLE
Constructor for VectorPtrView

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#77]
Hi, 
Recently, I'm trying to follow you beautiful code to learn DataFrame. While I'm reading file `include/DataFrame/VectorPtrView.h`, I'm confused by Constructor Function of VectorPtrView. I think VectorPtrView is packaging Vector, and Vector stores pointers. However, in your code, which I quoted here `inline VectorPtrView(const std::vector<T> &rhs)  { *this = rhs; }`, this is confusing me. Maybe this constructor should be in VectorView?

Sorry for my poor English.

**Comment by hosseinmoein** [comment]
I am currently out of power due to bad weather. When I get power back, I will answer you

**Comment by hosseinmoein** [comment]
@nehcuh ,

Both `VectorPtrView` and `VectorView` are _views_ into a vector data. It means they contain references (not the actual data) to another vector's data.
The difference between them is that `VectorView` is a view into a continuous block of memory. Therefore it only needs to keep track of the beginning and the end of the block. So, it is simpler and more efficient.
`VectorPtrView` is more generalized. It is a view into disjoint block(s) of memory. Therefore it need to store a pointer to each data item.   `inline VectorPtrView(const std::vector<T> &rhs) { *this = rhs; }` is just a convenient constructor to give you a view into a std::vector in one shot

**Comment by nehcuh** [comment]
Let's assume that we've constuct a `VectorPtrView` of a `vector`, then, using method of `VectorPtrView` such as `at`, `[]`, which would may result in errors. The method of `at` which I quote your realization here
```cpp
inline reference at(size_type n)  { return (*(vector_[n])); }
```
is not to give the element of the `Vector`, instead, it's assuming the element is a pointer.

Is there any misunderstanding?

**Comment by nehcuh** [comment]
BTW, is `VectorPtrView` lack of override of operator '>' and '!='?
