### ISSUE TITLE
Question of HeteroPtrView Constructor

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#78]
Hi Hosseinmoein,

When I'm reading your excellent code, I've got confused of your use of `unordered_map`. 

In your code `include/DataFrame/Vectors/HeteroPtrView.h`, you've set a private member which I quote here 
`template<typename T>
    inline static std::unordered_map<const HeteroPtrView *, VectorPtrView<T>>
        views_ {  };`.

Then in `include/DataFrame/Vectors/HeteroPtrView.tcc`,  the constructor method 

`template <typename T>
HeteroPtrView::HeteroPtrView(VectorPtrView<T>& vec)`, 

you've used a `push_back` method which `unordered_map` unsupported, is there something wrong?

## `HeteroPtrView.h`

<img width="751" alt="01" src="https://user-images.githubusercontent.com/36597254/90088501-ab0bfb00-dd51-11ea-8398-687df20db32e.png">

## `HeteroPtrView.tcc`

<img width="810" alt="02" src="https://user-images.githubusercontent.com/36597254/90088512-b2330900-dd51-11ea-96fd-024466999fc4.png">

**Comment by hosseinmoein** [comment]
You are right. I will fix it.
I guess this constructor was never used any where. That's why I never noticed it
Thanks
