### ISSUE TITLE
Prefix include folder with DataFrame

### ISSUE THREAD

**Issue by malkia** [hosseinmoein/DataFrame#8]
It'll be safer to integrate this in projects, if the include folder itself had DataFrame/ folder in there, e.g.
instead of include/DataFrame.h to be include/DataFrame/DataFrame.h - this way any extra includes in this folder won't collide with existing others (from other packages).

In short it's better to have

#include "DataFrame/DataFrame.h" (or #include <DataFrame/DataFrame.h>) rather than
#include "DataFrame.h" or (#include <DataFrame.h>)

**Comment by malkia** [comment]
For example looking for other projects that might include "BaseContainer.h" that's part of your include folder: https://github.com/search?l=C%2B%2B&q=%22BaseContainer.h%22&type=Code - this was my main concern :)

**Comment by justinjk007** [comment]
Yikes, Cmake config might need some changes to I think.

**Comment by hosseinmoein** [comment]
I guess if it is easy, let's do it. if not, let's wait until you are done with `Matrix`

**Comment by hosseinmoein** [comment]
I haven’t built in with cmake yet. Maybe it is part of cmake but it is not in git

**Comment by justinjk007** [comment]
Oh the install manifest is generated when you build with cmake if you follow the steps on README, it will be in your build folder.

**Comment by justinjk007** [comment]
@malkia Where the header files not installed under the prefix already, look at the last line in the install command in the CMake file

```
install(TARGETS ${LIBRARY_TARGET_NAME}
        EXPORT  ${PROJECT_NAME}
        LIBRARY       DESTINATION "${CMAKE_INSTALL_LIBDIR}"                            COMPONENT shlib
        ARCHIVE       DESTINATION "${CMAKE_INSTALL_LIBDIR}"                            COMPONENT lib
        RUNTIME       DESTINATION "${CMAKE_INSTALL_BINDIR}"                            COMPONENT bin
        PUBLIC_HEADER DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/${LIBRARY_TARGET_NAME}" COMPONENT dev)
```

installs under `../../include/Dataframe/`

**Comment by hosseinmoein** [comment]
got it. thx

**Comment by justinjk007** [comment]
I found a problem, unlike on linux, the installation does not happen on windows, As on there is no place to move the files to unlike unix platforms. So on linux `#include <Dataframe/Dataframe.h>` will work but on windows only `#include <Dataframe.h>` will. Because on windows, the external targets looks for header files in the `Dataframe/include` so to get the same behaviours  `#include <Dataframe/Dataframe.h>` we should change the directory structure of the include directory to have a additional `Dataframe` subdirectory.
