### ISSUE TITLE
Are there APIs for conditionally filtering and deduplications.

### ISSUE THREAD

**Issue by zainryan** [hosseinmoein/DataFrame#82]
Hi, thanks for this great library! I'm trying to implement some python pandas workloads using this Dataframe library. I took a look at the documentation page and don't find some commonly-used pandas APIs, in particular, conditionally filtering and deduplication. Could you educate me what is the most convenient way for implementing them here?

**Comment by hosseinmoein** [comment]
I am not sure what you are exactly trying to do, but I think DataFrame covers most of the Pandas functionalities and some more.
The `table of features` is here:
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/DataFrame.html

Based on what you wrote, I can also suggest:
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/get_data_by_loc.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/get_data_by_rand.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/get_data_by_sel.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/remove_data_by_loc.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/remove_data_by_sel.html
https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/replace.html
