### ISSUE TITLE
Question on VectorPtrView

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#83]
Sorry to reopen this question.

Let's assume that we've constuct a VectorPtrView of a vector, then, using method of VectorPtrView such as `at`, `[]`, which would may result in errors. The method of at which I quote your realization here

inline reference at(size_type n)  { return (*(vector_[n])); }
is not to give the element of the Vector, instead, it's assuming the element is a pointer.

Is there any misunderstanding?

Also, is `VectorPtrView` lack of realization of operator '!=' and '>'?

**Comment by hosseinmoein** [comment]
The whole point of view vector objects is to have references (not copies) to an original data vector. So the view vector content is always pointers

**Comment by nehcuh** [comment]
```cpp
    inline VectorPtrView(const std::vector<T> &rhs)  { *this = rhs; }
    inline VectorPtrView(std::vector<T> &rhs)  { *this = rhs; }
```
Such codes mean `VectorPtrView` will hold pointer of `rhs`?
 Sorry for my bad cpp program skill and a lot of thanks for your patience!

**Comment by hosseinmoein** [comment]
Yes. they are defined in these operators
```
inline VectorPtrView &operator = (const std::vector<T> &rhs)
inline VectorPtrView &operator = (std::vector<T> &rhs)
```

**Comment by nehcuh** [comment]
Thanks! 😄
