### ISSUE TITLE
iterator of VectorPtrView

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#84]
Hi Hosseinmoein,

Sorry to disturb again!

In your code `VectorPtrView.h`, you've defined `iterator`, `const_iterator` and `const_reverse_iterator`, each class holds an constructor like 
```cpp
        inline const_iterator (pointer const *node) noexcept
            : node_ (node)  {   }
```
However, the method of `++` operation trys to convert a `const**` instead of `value_type*const*` to `iterator`, is there's something wrong?
```cpp
inline const_iterator operator ++ (int) noexcept  {

            value_type const  **ret_node = node_;

            node_ += 1;
            return (const_iterator (ret_node));
        }
```

**Comment by hosseinmoein** [comment]
Yeah, I don't see an issue with that. Can you show me a practical issue with an example?

**Comment by nehcuh** [comment]
I'm not quite sure if demo listed below is ok? I've modified from your test code `vector_ptr_view_test.cc`. I've added some code after instantiation of `VectorPtrView` which is variable `vecview`,
```cpp
    VectorPtrView<int>::const_iterator item = vec_view.begin();
    std::cout << *item << std::endl;
    // std::cout << *(item++) << std::endl; // compilation error
    std::cout << *(++item) << std::endl;
```

**Comment by nehcuh** [comment]
```
error: no viable conversion from 'hmdf::VectorPtrView<int>::iterator::iter_type' (aka '__wrap_iter<int **>') to
      'hmdf::VectorPtrView<int>::iterator::value_type **' (aka 'int **')
            value_type   **ret_node = node_;
```

**Comment by hosseinmoein** [comment]
Thanks, your code snippet works fine. Do you mean this is not working
```
std::cout << *(item++) << std::endl;
```

I just pushed a fix to master

**Comment by nehcuh** [comment]
Got it! Thanks!
