### ISSUE TITLE
Constructor of HeteroView

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#85]
Hi Hosseinmoein, 

Sorry to disturb again!
While I'm reading your code of file `HeteroVector.tcc`, the code 
```cpp
template<typename T>
HeteroView HeteroVector::get_view(size_type begin, size_type end)  {

    std::vector<T>  &vec = get_vector<T>();

    return (HeteroView(
        &(vec[begin]), end == size_t(-1) ? &(vec.back()) : &(vec[end])));
```
confused me. 

In file `HeteroView.h`, the constructor accepts pointers as input as code described below
```cpp
template<typename T>
    HeteroView(T *begin_ptr, T *end_ptr);
```
and to get address of iterator can be written as 
```cpp
HeteroView(&(*vec[begin]), end==size_type(-1)? &(*vec.back()) : &(*vec[end]));
```

Is there some misunderstanding ?

**Comment by nehcuh** [comment]
Also, `DataFrameTypes.h` has a spelling mistake, you've written 'sigmiod` instead of `sigmoid`

**Comment by hosseinmoein** [comment]
I fixed the typo, thanks
I don't see any problem with the constructor. '[]' operator always returns a reference.

**Comment by nehcuh** [comment]
Yes, my fault. Thanks!
