### ISSUE TITLE
Aggregation operations after groupby()

### ISSUE THREAD

**Issue by zainryan** [hosseinmoein/DataFrame#86]
Hi!
Aggregation after groupby is a common operation in Pandas. I found DataFrame library supports sum after groupby via GroupbySum. I'm curious if there are more supported aggregation functions, say, max, min, and median.

**Comment by hosseinmoein** [comment]
Yes, currently I only have the groupby sum. But it is easy to add the others. I will add them as time permits. In the meanwhile I welcome contributions if you feel like it. We

**Comment by hosseinmoein** [comment]
@zainryan ,
I streamlined the groupby function and added more aggregator functors for group-by.
Please see https://htmlpreview.github.io/?https://github.com/hosseinmoein/DataFrame/blob/master/docs/HTML/groupby.html

**Comment by zainryan** [comment]
Thanks, it's very useful!
