### ISSUE TITLE
Question of LIBRARY_API 

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#88]
Hi, Hosseinmoein,

In your code of `VectorView.h` and `VectorPtrView.h`, you've defined class of `VectorConstView` and `VectorPtrConstView`. However, there is no `LIBRARY_API` put front of class definition, is there any consideration?

**Comment by hosseinmoein** [comment]
I just corrected that, thanks
I am not Windows expert nor do I have access to a Windows development environment. But, from what users told me so far, if you compile DataFrame using cmake on Windows, that shouldn't matter.

If you are a Windows development expert and willing to contribute, it would be nice if you could make DataFrame into a Visual C++ project.

Best,
HM

**Comment by nehcuh** [comment]
I'd like to do contribution to this great project. However, I'm just junior in Cpp, hope a few months later, I could contribute useful code.
Again, thanks to your code, I'm trying to learning c++- from your code.
