### ISSUE TITLE
Improvement of `VectorPtrView.h` copy assignment 

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#90]
Hi Hosseinmoein,

In your code of `VectorPtrView.h`, you've assign `reserve` before the copy assignment. However, you just reserve the default
class `VectorPtrView`, do you mean to reserve the temporary `tmp_vec` due to the `push_back` operatoration?
<img width="736" alt="001" src="https://user-images.githubusercontent.com/36597254/94902465-c7fbb980-04ca-11eb-8980-531d7464ba73.png">
Maybe, code should be written as
```cpp
    inline VectorPtrView &operator = (const std::vector<T> &rhs)  {

        VectorPtrView   tmp_vec;
        const size_type vec_size = rhs.size();
        reserve(vec_size);
        tmp_vec.reserve(vec_size);
        for (size_type idx = 0; idx < vec_size; ++idx)
            tmp_vec.push_back(&(rhs[idx]));
        swap(tmp_vec);
        return (*this);
    
```

**Comment by hosseinmoein** [comment]
The code is fine the way it is. You only need to reserve space for the vector you are loading

**Comment by nehcuh** [comment]
Sorry, I cann't fully understand what you mean.
The `VectorPtrView` clas of `tmp_vec` is an empty `VectorPtrView` at first, then the code is trying to `push_back` element 
into `tmp_vec`, would `tmp_vec` reserve its capacity during the `push_back` operation?

**Comment by hosseinmoein** [comment]
Yes
