### ISSUE TITLE
New versions missing in Conan

### ISSUE THREAD

**Issue by CedricFR** [hosseinmoein/DataFrame#92]
Hi,

Thank you for the great work.

I can see that on [conan-center ](https://conan.io/center/dataframe) latest version available for this package is 1.8.0. Now you have released 1.12.0.

Could you bring latest versions on conan-center? Or don't you plan to support this repository going forward?

Cheers

**Comment by hosseinmoein** [comment]
@CedricFR ,

The Conan was setup by @yssource . I am not very familiar with Conan. But it appears I don't have the permission to update it. I have emailed them for assistance.

Best,
HM

**Comment by yssource** [comment]
@hosseinmoein 
I've seen you asking to be a member of [EAP](https://github.com/conan-io/conan-center-index/issues/4#issuecomment-707812316) .
I think you are the best one to maintain the conan package. 
Meanwhile I'll try to update the conan package to the latest version this week, and share my work with you.

**Comment by hosseinmoein** [comment]
Actually I am in the middle of doing it. If you don’t mind, let me do it this time so I go through the whole procedure.
Thanks

**Comment by CedricFR** [comment]
Thank you!
