### ISSUE TITLE
copy assignment of `VectorPtrView.h` has bug

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#93]
In file `VectorPtrView.h`, the override of operator `=` which accepts parameter as `const std::vector<T>` may have a improper use.
<img width="575" alt="001" src="https://user-images.githubusercontent.com/36597254/96684279-ee1bc780-13ad-11eb-856b-a210c7467167.png">
The pointer of element of `const vector<T>` is `const T*`.
Blow is my test code
```cpp
    const std::vector<int> civec{0, 1, 2, 3};
    VectorPtrView<int> cvpw = civec;
    std::cout << cvpw.size() << std::endl
```

**Comment by hosseinmoein** [comment]
You are right. I fixed it
thanks
