### ISSUE TITLE
Function of `clear()` has no definition of `HeteroPtrView.h`

### ISSUE THREAD

**Issue by nehcuh** [hosseinmoein/DataFrame#94]
Hi Hosseinmoein,
While reading your code of `HeteroPtrView.h`, I've found no definition of declarasion of function `void clear()`.
Is there any consideration?
<img width="610" alt="001" src="https://user-images.githubusercontent.com/36597254/96885845-936d9300-14b5-11eb-9d1c-f054d5408ce6.png">

**Comment by hosseinmoein** [comment]
It is defined in `src/Vectors/HeteroPtrView.cc`.
