### ISSUE TITLE
Remove duplicates by single columns

### ISSUE THREAD

**Issue by Botched135** [hosseinmoein/DataFrame#97]
Hi,
I have been using pandas quite a bit, so I was so happy when I found this as I highly prefer using C++ over Python.

One thing that seems to be missing according to my use case, is remove duplicates based on a single column. As I see it, this help cull entries from the data, that might not be relevant, given the wrong ID or e.g. for my case I use it to remove tracks with the same name. Is there any particular reason there is no implementation for this?

**Comment by hosseinmoein** [comment]
No particular reason. I didn't need it at the time.
I will add it in a few days

Best,
HM

**Comment by Botched135** [comment]
That is so awesome. Thank you!

**Comment by hosseinmoein** [comment]
@Botched135 , this is done in master branch

**Comment by Botched135** [comment]
@hosseinmoein Thank you so much. I am going to start experimenting right now
