### ISSUE TITLE
C++ newbie question: How to compile the library with my own main.cpp?

### ISSUE THREAD

**Issue by Asocius** [hosseinmoein/DataFrame#98]
Hello there,

complete newbie at C++ and CMake here (coming from Python Pandas). How do I compile the library with my own main.cpp file? Do I have to add something like add_executable(${PROJECT_NAME} main.cpp) to the CMakeLists.txt file or something completely different? I have Visual Studio 2019 installed and clicked on Build->Install DataFrame and it all ran through without errors, also the built-in tests seem to work, but I don't know what the "next" step is.

Best regards
Stephan

**Comment by hosseinmoein** [comment]
You can just follow/duplicate what is happening for ‘dataframe_tester.cc’ in the cmake file.

**Comment by Asocius** [comment]
Thanks for the quick reply, now it works!
